### ISSUE TITLE
Configure elasticsearch cluster

### ISSUE THREAD

**Issue by fsteeg** [lobid/lodmill#120]
see http://blog.liip.ch/archive/2013/07/19/on-elasticsearch-performance.html

**Comment by acka47** [comment]
This probably can be closed, @fsteeg , @dr0i ...

**Comment by dr0i** [comment]
Yes this is outdated, also we have done most of what is proposed in the blog post AND something more (i.e. set `dynamic` to `false`, see #666).
Only thing left is waiting for the SSDs :).
Closing.
