### ISSUE TITLE
Enable push service

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#132]
With elasticsearch as the backend, it is easy to implement an information push service (or: "subscribe" service). One would register some queries, say "give me all docs wich are categorized with [ddc:540](http://dewey.info/class/540/) and which contains the string 'photon' " etc. . Every new indexed document could then be checked against these registered queries using [elasticsearch's percolator](http://www.elasticsearch.org/blog/percolator/) . The matched docs can then be pushed to the one who subscribed the registered query. Thus, a desiderat of Klaus Tochtermann can be fullfilled (German, [section 4 "Content kommt zum Forschenden"](http://www.zbw-mediatalk.eu/2013/08/klaus-tochtermann-zehn-thesen-zum-zukunftigen-profil-von-wissenschaftlichen-informationsinfrastruktureinrichtungen-mit-uberregionaler-bedeutung/))

**Comment by acka47** [comment]
This probably still is relevant in the API 2.0, and might also be of interest for customers like UB Dortmund that get daily updates from lobid 2.0. Am I right?

**Comment by acka47** [comment]
We now have RSS, at least. Closing as nobody asks for this.
