### ISSUE TITLE
Implement OpenRefine reconciliation API

### ISSUE THREAD

**Issue by tfmorris** [lobid/lodmill#168]
It'd be useful to have a reconciliation service which could be used directly with OpenRefine.  Such as service could be built as a broker to the existing API, but it'd be a) easier to find and b) more powerful if implemented natively.

Ideally a reconciliation service would taken into account more than just a name match.  Having the ability to specify things like nationality, birth, & death date in the scoring would provide for better quality matches and less human review.

Documentation of the API is available here: https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API and there are some simple example implementations on Github too, such as https://github.com/OpenRefine/reconciliation_service_skeleton

**Comment by hauschke** [comment]
Two Marches later: Is there any progres on this?

**Comment by fsteeg** [comment]
We've started working on an OpenRefine reconciliation service for lobid-organisations.

See https://github.com/hbz/lobid-organisations/issues/55#issuecomment-129771979 for details.

**Comment by acka47** [comment]
Implemented for lobid-organisations. No request yet to add this for lobid-resources. Closing.
