### ISSUE TITLE
Enable geo search

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#247]
With [elasticsearch it is possible to have an array of geo locations assigned to a record](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-filter.html). 
If we would resolve the lobid-organisation URIs associated to items and get the geo lat/lon from there , we could construct the geolocation ES needs. We then would be able to make geo searches, e.g. "give me all books authored by 'Saussure' near 5 km from location X".

**Comment by acka47** [comment]
We took account of this with beta.lobid.org/organisations. Closing.
