### ISSUE TITLE
Testfile HT014015351: add type "EditedVolume"

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#271]
it sems that - similar to the approach with maps (see #270) - "Aufsatzsammlungen" (=anthology; collection of essays) is also typed via subject indexing, i.e. adding the string "Aufsatzsammlung" to the 900s. Maybe we could use this infromations omehow. But I couldn't find  class for this type of resource. (We could start with using ```bibo:Collection```.)

**Comment by acka47** [comment]
I will create a new class `http://purl.org/lobid/lv#Anthology`. Please use this to type anthologies.

**Comment by acka47** [comment]
I decided that `lv:EditedVolume` is the better term, see https://github.com/lobid/vocabs/issues/37#issuecomment-73516193.

**Comment by dr0i** [comment]
Deployed to staging, see http://test.lobid.org/resource/HT014015351.

**Comment by acka47** [comment]
I can't see the type `lv:EditedVolume` right now.

**Comment by acka47** [comment]
I can see it now, but it is at the wrong place. Should be under `@type`.

**Comment by dr0i** [comment]
Updated the test data. Seems to be fine.

**Comment by acka47** [comment]
+1 Looks good on staging, see http://test.lobid.org/resource?q=*&type=http://purl.org/lobid/lv%23EditedVolume.

**Comment by acka47** [comment]
In the end, I *did* find an issue with this, see #683. Closing this one anyway.
