### ISSUE TITLE
Testfile HT014525099: no role specification for vocal parts

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#272]
http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT014525099 sepcifies the Alt and Sopran vocal parts. Currently, we don't use this information. We should at least map both to http://id.loc.gov/vocabulary/relators/sng.

**Comment by ChristophEwertowski** [comment]
Done in [issue](https://github.com/hbz/lobid-resources/issues/3), see [comment](https://github.com/hbz/lobid-resources/issues/3#issuecomment-287301520) and [line in morph](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/morph-hbz01-to-lobid.xml#L1405). See [example resource](http://lobid.org/resources/HT014525099).
Closing this issue.
