### ISSUE TITLE
Testfile HT015082724: Problems with publisher & type

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#273]
Somehow publication places made it into the list of publishers (`dc:publisher`).

Currently (incorrect):

```
<http://lobid.org/resource/HT015082724> <http://purl.org/dc/elements/1.1/publisher> "Amersfoort", "Groningen", "Noordhoff", "Van Gorcum", "Wolters-Noordhoff" .
```

Correct would be:

```
<http://lobid.org/resource/HT015082724> <http://purl.org/dc/elements/1.1/publisher> "Noordhoff", "Van Gorcum", "Wolters-Noordhoff" .
```

The publication statement also looks quite strange with the many publishers and places.

Another problem: The resource is typed as `bibo:Book` and `bibo:Collection` although `bibo:Issue` would be the correct class.

**Comment by dr0i** [comment]
The `pubisher`-problem seems to be gone (so it seems also that the data has changed and I can't really follow this).
However the `type`-problem seems to be acute.
Also, would be nice to have two issues for the these (not connected) problems.

**Comment by acka47** [comment]
I opened a new issue at https://github.com/hbz/lobid-resources/issues/123 for the type problem. Closing this one.
