### ISSUE TITLE
RDFa: show dcterms:subject AND dc:subject

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#308]
This was reported by @jschnasse :

http://lobid.org/resource/HT016522861
Triples with predicate http://purl.org/dc/elements/1.1/subject do not show up in rdfa.

`<http://lobid.org/resource/HT016522861> <http://purl.org/dc/elements/1.1/subject> "Denkmalrecht"^^<http://www.w3.org/2001/XMLSchema#string> .`

**Comment by acka47** [comment]
Wow 2.0. Such UI. Much fields. Closing.
