### ISSUE TITLE
Resolve GND person data not only of creator but of all persons

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#310]
For example : 
`<http://lobid.org/resource/HT014015351> <http://id.loc.gov/vocabulary/relators/hnr> <http://d-nb.info/gnd/136788548> .'
To identify  all predicates which describes persons have a look at the [JSON-LD context](https://github.com/lobid/lodmill/blob/master/lodmill-ui/public/contexts/lobid-resources.json), especially the loc-relators.

**Comment by dr0i** [comment]
Deployed to production.

**Comment by acka47** [comment]
+1. Closing.
