### ISSUE TITLE
use blank nodes for unqualified creators and contributors

### ISSUE THREAD

**Issue by jschnasse** [lobid/lodmill#311]
Sometimes authors as well as corporate bodies are only present as literals. For those cases lobid uses dc-elements instead of dc-terms to signal that no URI for the person or the institution is available. This raises a number of problems.
1. dcterms:creator is used for both: persons and corporate bodies. If no GND-ID is linked in, it is not possible to determine the type of the creator.
2. Roles of contributors can not be linked to literals using loc:relators

I'd suggest to use blank nodes for creators and contributors. I'd also like to suggest to use GND Vocabulary to express type information and the actual name using gnd:preferredName. 

This would also provide a solution for #290.

Maybe for subjects the situation is similar...

**Comment by acka47** [comment]
I think we can close this issue as @jschnasse seems to be content with the current solution. Or do you still want bnodes?

**Comment by dr0i** [comment]
Closing this.

**Comment by jschnasse** [comment]
not +1 from me! Why close?

**Comment by acka47** [comment]
This should best be implemented as subticket of https://github.com/hbz/lobid/issues/1.

**Comment by dr0i** [comment]
To give an update on this issue:
- tosee what's the status quo, here is an example: http://lobid.org/resources/HT018700720. You can see that a blank nodes for unqualified  contributors are already implemented. What's missing so is the `role` of the contributor. This will be done with hbz/lobid-resources#38.
  I would like @jschnasse to close this issue as we have hbz/lobid-resources#38. Or am I missing something here ?

**Comment by dr0i** [comment]
ping @jschnasse and have a look at  hbz/lobid-resources#38.

**Comment by dr0i** [comment]
Hi @jschnasse , since hbz/lobid-resources#38 is closed I will close this issue too.
