### ISSUE TITLE
Performance tuning  : hadoop converting and elasticsearch indexing

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#331]
These ideas may be fine or not, and some tuning may be missing here.

# elasticsearch
For now, it takes ca 2h alone to convert the lobid-items. Indexing takes 
Worse even, indexing AND querying is not possible since the queries take too much time. Ideas to improve indexing:

1. use `refresh_intervall=-1` before indexing (so querying should be no problem, at least till ->) set it back to `1s` after indexing, see [java-code](http://elasticsearch-users.115913.n3.nabble.com/setting-the-refresh-interval-from-Java-API-td4032741.html)
2. it may be nice to use the `upsert` (update or insert) to [save some network roundtrips](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-update.html) 
3. it may be nice to use zipped file(s) when loading from hdfs to reduce I/O load (see -> "hadoop" below)

# hadoop
it may be nice to zip the file(s) when copying to hdfs to reduce I/O load.

**Comment by acka47** [comment]
@dr0i Can we close this one?

**Comment by dr0i** [comment]
Yes, closing, we don't work with hadoop anymore.
