### ISSUE TITLE
MAB 599: what properties to use?

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#333]
As @acka47 describes in #261 there are sometimes objects-URIs wrongly created using an ISBN, e.g.:
 <http://lobid.org/resource/HT017022956> <http://purl.org/dc/terms/isPartOf> <http://lobid.org/resource/978-1-4051-6255-5> .

For now, the values of all subfields of MAB field 599 are prefixed with a lobid resource URI , but thats obviously wrong. 599- should be the hbz ID, 599s the ZDB ID (which will be linked directly to the ZDB linked data service) - but what is with the others:
ISBN,ISSN,ISMN and ISRN ? How could they be predicated?

**Comment by acka47** [comment]
Closing.
