### ISSUE TITLE
Support multiple short.X fields

### ISSUE THREAD

**Issue by fsteeg** [lobid/lodmill#345]
Based on a user request: support multiple fields using the `short.X` syntax to avoid multiple queries.

E.g. a request like `/resource?id=HT004542218&format=short.fulltextOnline,wikipedia` could return:

``` json
{
  "fullTextOnline" : [
    "http://gutenberg.org/ebooks/2814", 
    "http://gutenberg.org/ebooks/7872"
  ],
  "wikipedia" : [
    "http://wikipedia.org/wiki/Dubliners"
  ]
}
```

**Comment by acka47** [comment]
Won't fix in 1.0, I don't think we have a `short` parameter in 2.0. Closing.
