### ISSUE TITLE
Set up proper robots.txt files for staging and production

### ISSUE THREAD

**Issue by fsteeg** [lobid/lodmill#349]
We don't want staging to be indexed.

**Comment by acka47** [comment]
Currently, you will find results for api.lobid.org, test.lobid.org & staging.api.lobid.org in google, try e.g. some of these: http://stats.lobid.org/web-access/access_log.go.20150301.html#keyphrases

Thus, we need to write robots.txt for both sub domains that read like this:

```
# robots.txt for api.lobid.org
User-agent: *
Disallow: /
```
```
# robots.txt for test.lobid.org
User-agent: *
Disallow: /
```
```
# robots.txt for staging.api.lobid.org
User-agent: *
Disallow: /
```

**Comment by acka47** [comment]
We won't need a robots.txt for production as far as I can see as we don't want to exclude anything there from indexing, do we?

**Comment by dr0i** [comment]
Deployed for testing, test subdomains:
api:  http://api.lobid.org/robots.txt
test: http://test.lobid.org/robots.txt
staging.api.lobid.org: http://staging.api.lobid.org/robots.txt

see that root '/' is allowing indexing:
/: http://lobid.org/robots.txt

**Comment by acka47** [comment]
Looks good. Closing.

**Comment by dr0i** [comment]
ticket refers to hbz/nwbib#91.

**Comment by acka47** [comment]
There is a problem with the robots.txt for staging now, see http://test.lobid.org/robots.txt. Reopening.

**Comment by acka47** [comment]
looks fine now. closing.
