### ISSUE TITLE
Resources: Geo coordinates and geo searching

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#351]
Example data:  http://lobid.org/resource/HT017468042
To make use of elasticsearch's geo search we have to put more effort in the transformation mentioned in #350.  It woul be nice if the RDF data would
- look similar than what ES internally needs
- be expressed in best case with a property that could be used to describe a point AND a polygon

And don't forget : the property must describe the coordinates _on_ the map, not _of_ the map
As our data (e.g. "E 006 32 -E 008 51 /N 053 02 -N 051 38") don't use the WGS84 notation this should be transformed. Than we can decide what property to use ( e.g. points http://www.w3.org/2003/01/geo/wgs84_pos#lat_long or creating a point using bnodes and wgs84:lat and wgs84:lon ). For more background see http://www.w3.org/wiki/GeoRDF and http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html .

**Comment by acka47** [comment]
Still looks the same in 2.0. As far as I know, no API user has requested this yet. Those getting the data via lobid can transform the geo data as needed by themselves. Closing.
