### ISSUE TITLE
Index short keys in Elasticsearch

### ISSUE THREAD

**Issue by fsteeg** [lobid/lodmill#357]
To make the full Elasticsearch query language practically usable on the `q=` queries, we should index the JSON-LD using the same keys as served by the API (i.e. the short representations defined in the context). That format would still have to be JSON-LD expanded to retain a unique value format for each key.

**Comment by dr0i** [comment]
See also #433.

**Comment by dr0i** [comment]
Closing this one as it will be handled by hbz/lobid-resources#1 .
