### ISSUE TITLE
Number of API query results differs when using browser/rapper or curl

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#397]
This is strange. When I resolve http://lobid.org/subject?name=london+großbritannien&type=TerritorialCorporateBodyOrAdministrativeUnit in a browser I get one result.

When I do "rapper -o turtle http://lobid.org/subject?name=london+großbritannien&type=TerritorialCorporateBodyOrAdministrativeUnit" I also get one result (although the data doesn't follow prefix conventions).

When I use curl though - "curl http://lobid.org/subject?name=london+großbritannien&type=TerritorialCorporateBodyOrAdministrativeUnit" or curl -H "Accept: text/turtle" http://lobid.org/subject?name=london+großbritannien&type=TerritorialCorporateBodyOrAdministrativeUnit - I get > 1 results.

This doesn't seem ok to me. Why is this? Am I overlooking something?

**Comment by fsteeg** [comment]
Looks like curl cuts off the URL at some point. With a quoted URL I get 173 hits in the browser:

http://lobid.org/subject?name=london+gro%C3%9Fbritannien&type=http%3A%2F%2Fd-nb.info%2Fstandards%2Felementset%2Fgnd%23TerritorialCorporateBodyOrAdministrativeUnit&format=full

And with curl:

`curl "http://lobid.org/subject?name=london+gro%C3%9Fbritannien&type=http%3A%2F%2Fd-nb.info%2Fstandards%2Felementset%2Fgnd%23TerritorialCorporateBodyOrAdministrativeUnit&format=full"`

**Comment by dr0i** [comment]
> When I use curl though - "curl http://lobid.org/subject?name=london+großbritannien&type=TerritorialCorporateBodyOrAdministrativeUnit"  ...  I get > 1 results

You have to escape the query because an `&` is interpreted by the shell such that your query is cut into two separated commands.

**Comment by acka47** [comment]
Thanks. Closing.
