### ISSUE TITLE
Return a single XML root for multiple hits with RDF+XML

### ISSUE THREAD

**Issue by fsteeg** [lobid/lodmill#463]
Could be implemented analogous to oerworldmap, see:

https://github.com/hbz/oerworldmap/blob/16e620f1c1dea01963bc150f75c5e67c4cc69e6f/oer-api/app/controllers/oer/NtToEs.java#L150

Requires an update of the JSON-LD/Jena lib that we currently use in the api, and the conversation logic (don't transform each document separately).

See also #297 for origin of this.

**Comment by fsteeg** [comment]
Deployed to staging:

`curl -L --header "Accept: application/rdf+xml" http://test.lobid.org/resource?id=HT002189125`

**Comment by acka47** [comment]
+1
