### ISSUE TITLE
Add information to lobid on which libraries are "hbz libraries"

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#492]
Steps:
- [x]  Examine the item information and create a list of ISILs connected to lobid items .
- [ ]  Add information to each library indicating that their holdings are recorded in hbz union catalog/lobid.

The question is how to implement 2.
- The easiest way would be like we already added similar information from SIgelverzeichnis with `org:linkedTo <http://lobid.org/organisation/DE-605> .` (The problem with this approach could be that some libraries linked to hbz aren't cataloging in to the union catalg (e.g. DigiBib users). Will have to evaluate this.)
- Maybe we should add an entry for the hbz union catalog to lobid and link to there.

**Comment by dr0i** [comment]
Copied the list to http://lobid.org/download/dumps/DE-605/isilOfItems.txt.
Created it ,quickly and only reflecting the data up to 2015, this way : 
`nohup $(zgrep exemplar resources-dump.nt.gz |sed 's#.*lobid.org/item/.\{11\}:\(.*\):.*>.*#\1#g'|cut -d ':' -f1  |sort -u > isilOfItems1.txt) 2>&1`
where 'resources-dump.nt.gz' comes from http://lobid.org/download/dumps/DE-605/lod/resources-dump.nt.gz.
Would use a more sophisticated and more up-to-date method if needed.

**Comment by dr0i** [comment]
When @acka47 said 

> Add information to lobid on which libraries are "hbz libraries"

you mean "add to lobid-organisations", don't you?

**Comment by acka47** [comment]
> When @acka47 said 

>> Add information to lobid on which libraries are "hbz libraries"

> you mean "add to lobid-organisations", don't you?

Yes. Regarding the question how to add this information I suggest to add a link to the held resources of the library, e.g. somethin like this:

```json
{
  "id": "http://lobid.org/organisations/DE-38#!",
  "ex:holdings": "http://lobid.org/resources/search?owner=http%3A%2F%2Flobid.org%2Forganisations%2FDE-38"
}
```

We could then show the link in the HTML but would probably have to adjust lobid-resources so that the "owners" facet isn't reset with every new search.

**Comment by acka47** [comment]
Closing this. I think, when we plan to integrate lobid-resources result list in lobid-organisations again, it will be quite trivial to find a solution (and I am not sure whether we will actually need to add information to the RDF)...
