### ISSUE TITLE
Volumes don't have a title

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#498]
Some (all?) volumes don't have a title. The title should be contructed from the superordinated resource + volume information.

Example: http://lobid.org/resource/HT002888677

**Comment by acka47** [comment]
Examples (from NWBib): 
- http://lobid.org/nwbib/search?set=HT018653470 
- http://lobid.org/nwbib/search?set=HT018649250

Obviously, the whole title should be built from fields 331 and 90.


```
<datafield tag="090" ind1="-" ind2="1">
 <subfield code="a">2</subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="2">
  <subfield code="a"><<Die>> Open.NRW-Strategie</subfield>
</datafield>
```
Expected result: "Die Open.NRW-Strategie, 2"

```
<datafield tag="090" ind1="-" ind2="1">
<subfield code="a">1</subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="1">
<subfield code="a">A - G</subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="2">
<subfield code="a">Familienbuch Sieglar</subfield>
</datafield>
```

Expected result: "Familienbuch Siglar, 1. A-G"

**Comment by acka47** [comment]
We should implement this after or together with #711.

**Comment by dr0i** [comment]
Using the dot would result in "Die letzten Lebensjahre, 1963 - 1967, 2. September 1965 - April 1967" for  http://lobid.org/resource/HT015891797. Could easily be misinterpreted as "2. September". Thus better use comma.
In addition of the fields you mentioned the fields `089` resp. `090` are taken into account, see e.g. http://lobid.org/resource/HT015082724/about.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
looks good, except for one minor thing.

> In addition of the fields you mentioned the fields `089` resp. `090` are taken into account, see e.g. http://lobid.org/resource/HT015082724/about.

Generally, volume information from `090` should be preferred and `089` only be taken into account if there is no `090`. (As we already do for the volume information field.)

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1. We will most definitely have to do some adjustments in the future, though, on the data level or in NWBib where very similar information can now be found in the "Titel" and "In" field, see e.g. http://test.lobid.org/nwbib/HT018653636. /cc @fsteeg

**Comment by dr0i** [comment]
Deployed to production.

**Comment by fsteeg** [comment]
@acka47 Don't know what to change in NWBib exactly, and should probably be a separate issue.

**Comment by acka47** [comment]
Yes, this will be a new issue if any. Just wanted to let you know about this redundancy. I will also mention it in the mail to the list.
