### ISSUE TITLE
Remove duplication of dct:contributor and MARC relator properties

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#506]
For persons who are not an author but have contributed to a work we currently use dct:contributor as well as the respective MARC relator property.

Where a specific relator code is given, the redundant `dct:contributor` should be removed. (We must then add the marcrel properties to the fields to be searched e.g. by an "author" query.)

**Comment by acka47** [comment]
The `preferredName` literal got lost during the adjustment, i.e. the objects of `marcrel:editor` aren't described separately as is the case with `dct:creator` and `dct:contributor`. See. e.g. http://lobid.org/resource/HT015436381/about or http://lobid.org/resource/BT000142976/about.

In NWBib it's more obvious as URIs are shown where we need the name literals, see http://lobid.org/nwbib/HT015436381 and http://lobid.org/nwbib/BT000142976.

**Comment by dr0i** [comment]
Ready in the small test set , see http://test.lobid.org/nwbib/HT016135351 .
Configured to be indexed at weekend. Let's see if it performs fast enough ...

**Comment by dr0i** [comment]
Performs very well - doesn't seem to have any impact at all :+1: .
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
