### ISSUE TITLE
Do stress test with facetes on set NWBib

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#507]
Digibib wants to know how far can we go with facetes. For implementation of facets in the API see hbz/nwbib#33.
Todo:
-  create some thousand queries using facetting , e.g. like this one: http://test.lobid.org/resource/facets?field=@graph.http://purl.org/dc/terms/creator.@id&name=linguistik&size=5
- run them against test.lobid, starting with 10/s, then 50/s, ... 200/s.
- Watch the load , cancel if necessary
- log the needed time

**Comment by acka47** [comment]
Closing, as there was no further request by DigiBib colleagues.
