### ISSUE TITLE
Elasticsearch tuning: adjusting the mapping more closely to our need.

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#513]
Todo:
browse the list of all mapping fields in ES and adjust them as restrivtive as possible.

See https://github.com/lobid/lodmill/issues/331#issuecomment-36901777 and https://github.com/hbz/nwbib/issues/33#issuecomment-49022360 .

**Comment by acka47** [comment]
Wn#t fix for 1.0. Closing.
