### ISSUE TITLE
Incremental updates of hbz01 resources

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#573]
We should be able to ETL incremental updates.
Beware that those can only be made if the difference between old and new data *does not* include the change of:

- ES config index
- data model

See #541 for daily full updates (which allow changing of ES config index).
See #291 for changing also the data model (full transformation necessary).

**Comment by acka47** [comment]
@dr0i Please find out how long implementation of imcremental updates would take. After this we will update the prioritization.

**Comment by dr0i** [comment]
Since 31f7cea5111e58b57846926f2b3b55450fb56e7c we already have the daily incremental updates as RDF transformated data in mysql table. So todo is just to write an EsDocumentUpdater using http://www.elasticsearch.org/guide/en/elasticsearch/client/java-api/current/java-update-api.html#java-update-api .
Takes a day.

**Comment by acka47** [comment]
A day sounds good. So please go ahead and implement this on Monday. ;-)

**Comment by dr0i** [comment]
Tested. A daily update of an 9MB file took 90 minutes.
Deployed to production.

**Comment by dr0i** [comment]
Updates are done on the newest index. If this newest index is a test index, the test index is updated. Which was not intended. As there are other problems mixing  test and productive indices I will use quaoar1 ,(that's another ES cluster) for testing.
It's possible to implement some more logic to have prodiuctive and test indices on the same cluster but, of course, but no need yet.
