### ISSUE TITLE
Look-up tables in morph-enriched

### ISSUE THREAD

**Issue by SBRitter** [lobid/lodmill#628]
There are two look-up tables / maps in morph-enriched.xml that have to be updated with their new location as they are still referring to http://test.lobid.org/assets/data/

Updated lines should look like this:
\<filemap name="country-map" files="http://lobid.org/download/lookup-tables/data/country-map.csv" /\>
\<filemap name="isil2dbpedia_map"files="http://lobid.org/download/lookup-tables/data/isil2dbpedia-map.csv" /\>

At the moment, these files are not available yet.

**Comment by acka47** [comment]
Can we close this issue?

**Comment by SBRitter** [comment]
I think so.

**Comment by acka47** [comment]
Closing.
