### ISSUE TITLE
Wrongly typed as Book AND ArchivedWebPage

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#637]
This one is reported by @literarymachine:
Looking at [edoweb resources](http://lobid.org/resource?set=edoweb) these are typed as `Book` *and* `ArchivedWebPage`. They shouldn't be also books.

**Comment by dr0i** [comment]
Deployed to staging , see e.g. http://test.lobid.org/resource?id=TT002234459.

**Comment by acka47** [comment]
+1 (The next step should be to remove `frbr:Manifestation` typing, see hbz/lobid#118.)

**Comment by dr0i** [comment]
Deployed to production, closing.
