### ISSUE TITLE
Remove types frbr:Manifestation and dct:BibliographicResource

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#639]
As these are assigned to all or (in the case of frbr:manifestation) nearly all resources, they aren't of much use. We can omit `frbr:Manifestation` and `dct:BibliographicResource` from the data without much trouble.

**Comment by acka47** [comment]
@jschnasse As you seem to be eager to clean up typing of resources in lobid, would you like us to prioritize this ticket as well?

**Comment by acka47** [comment]
This should be implemented together with hbz/lobid#164.

**Comment by jschnasse** [comment]
dct:BibliographicResource is used by regal-drupal. It provides kind of fall back if no other type can be recognized. I'm sure we can change our implementation (@literarymachine), but for the moment please do not remove!
frbr:Manifestion is ok to remove.

**Comment by dr0i** [comment]
@acka47 I not sure what to do now.  `frbr:Manifestation` seems to be handled in an other ticket. But what about `dct:BibliographicResource` - should I work on that?

**Comment by jschnasse** [comment]
no work  on dct:BibliographicResource needed! Ok, as is!

**Comment by acka47** [comment]
To be clear:
:exclamation:  **`dct:BiboliographicResource`** won't be removed :exclamation:

**Comment by dr0i** [comment]
Deployed to staging and production.
