### ISSUE TITLE
Remove double typing of bibo:Journal/Series and lv:Misc

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#676]
If we have a clear type like `bibo:Journal` on our resources we shouldn't also have it typed as `lv:Miscellaneous`. 

There are many such resources, see http://lobid.org/resource?q=*&type=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FPeriodical.

**Comment by acka47** [comment]
If now more informative type exists, lv:Misc should of course be kept.

**Comment by dr0i** [comment]
Deployed to production, please have a look.

**Comment by acka47** [comment]
+1 Looks good. Closing.
