### ISSUE TITLE
Some EditedVolumes missing bibo:Book typing

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#683]
With https://github.com/lobid/lodmill/pull/680 some resources lost the `bibo:Book` type they previously had. Examples:
- http://lobid.org/resource/HT012777456/about
- http://lobid.org/resource/HT016589481/about
- http://lobid.org/resource/HT017738940/about

**Comment by ChristophEwertowski** [comment]
Now they have both the type `EditedVolume` and `Book`. See [HT012777456](http://lobid.org/resources/HT012777456?format=json) / [HT016589481](http://lobid.org/resources/HT016589481?format=json) / [HT017738940](http://lobid.org/resources/HT017738940?format=json). Closing this issue.
