### ISSUE TITLE
Some resources are incorrectly collectedBy NWBib

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#688]
Examples:
http://lobid.org/resource/HT015440386
http://lobid.org/resource/HT015437369

The problem seems to be with taking 700n as indicator for NWBib, see [line 1259 in morph](https://github.com/lobid/lodmill/blob/f2813be35af1b56cc9812377e86031661c2efb09/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1259).

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1. But please leave it on staging for now so that customers are able to check out the differences.

**Comment by dr0i** [comment]
Deployed to production, as discussed at phone.
