### ISSUE TITLE
Provide list of resources with 700n but without 078n

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#691]
With https://github.com/lobid/lodmill/commit/2c7d7cfa272081602263a41d12802e9b798ca8ff 3188 resources where removed from the NWBib set. NWBib editors want to take a deeper look at those resources as they probably should be part of NWbib and just the selection field 078n wasn't populated as needed.

@dr0i, please create a list of hbz IDs of these 3188 resources and I will send it to the mailing list.

**Comment by dr0i** [comment]
For the list see http://lobid.org/download/dumps/DE-605/nwbib/700nOhne078n_sortedUniq.txt.
Lists will be generated with every hbz01 transformation because it's part of the productive code.

**Comment by acka47** [comment]
> Lists will be generated with every hbz01 transformation because it's part of the productive code. 

With generating the list new resources will be added but corrected resources (where 078n is added) won't be removed.

**Comment by acka47** [comment]
+1. Closing
