### ISSUE TITLE
For NWBib resources, add all links in field 655u to RDF with lv:fulltextOnline

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#700]
There are some online resources marked as such with the triple `_: dct:medium http://rdvocab.info/termList/RDACarrierType/1018` (online resource) that don't have a link in the RDF. Examples:
- http://lobid.org/resource/HT018400499
- http://lobid.org/resource/HT014018569
- http://lobid.org/resource/HT014018545

All of them have a link in 655u, e.g. example 1 from above:

```xml
 <datafield ind2="1" ind1="e" tag="655">
            <subfield code="u">http://nbn-resolving.de/urn:nbn:de:hbz:6:2-23936</subfield>
            <subfield code="x">
              Online-Ausgabe des Titels ist Ã¼ber Westfalica electronica verfÃ¼gbar.
            </subfield>
</datafield>
```

At least for NWBib resources, we should add these links to the RDF (with `lv:fulltextOnline`) without any further considerations.

**Comment by dr0i** [comment]
@acka47 have a look at the junit test set.

**Comment by acka47** [comment]
I commented inline. Furthermore,  the content of `webPageArchived` should not also be added to `fulltextOnline`.

**Comment by dr0i** [comment]
Overturned the redundant data, see https://github.com/lobid/lodmill/commit/49d924faa2a2030198340b4200f6a2d6c71fd08c.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://test.lobid.org/resource/HT014018545/about and http://test.lobid.org/resource/HT018400499/about and http://test.lobid.org/resource/TT002234459/about, the latter also beeing a webPageArchived.

**Comment by acka47** [comment]
+1 Looks good in lobid but I wonder why the fulltext link isn't shown in http://test.lobid.org/nwbib/HT014018545. Doesn't test-nwbib point to the test.lobid? If this is the case, we will have to do some adjustments in NWBib.

**Comment by dr0i** [comment]
Right, the test-nwbib was set to lobid production. Changed that now.

**Comment by acka47** [comment]
Good to know, so we don't have to adjust anything in NWbib...

**Comment by dr0i** [comment]
Deployed to production, closing.
