### ISSUE TITLE
Add lv:contained in as specific isPartOf property for articles

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#702]
As specific property for articles in a journal, edited volume etc. (examples: http://lobid.org/nwbib/HT017306644, http://lobid.org/nwbib/HT018408723; [morph, line 1233](https://github.com/lobid/lodmill/blob/f2813be35af1b56cc9812377e86031661c2efb09/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1233)) we will use – in addition to the current `dct:isPartOf` :exclamation: – `lv:containedIn` (to be created, see lobid/vocabs#39).

**Comment by dr0i** [comment]
Deployed small test set to staging. Unfortunately your exampes are not part of that test set. Is e.g. http://test.lobid.org/nwbib/HT017529028 ok, though? See the diff for what fields are mapped.

**Comment by acka47** [comment]
:exclamation: Note: `containedIn` is to be used on articles linking them to a series or a book and the needed data comes from field 599, see  [morph, lines 1285-1292](https://github.com/lobid/lodmill/blob/783ce3b303d4b415866802ad3a32cc6c44cbfa57/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1285-L1292)

> Is e.g. http://test.lobid.org/nwbib/HT017529028 ok, though?

I can't find `lv:containedIn` in the RDF of http://test.lobid.org/resource/HT017529028. As the resource is a book and has no data in field 599 this is correct. 

Examples from test where `lv:containedIn` should occur can be found in http://test.lobid.org/resource?q=*&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FArticle. Here are the articles from the test set where it already works:

- http://lobid.org/resource/BT000040377
- http://lobid.org/resource/BT000041593
- http://lobid.org/resource/BT000067443
- http://lobid.org/resource/BT000128754
- http://lobid.org/resource/HT013577568
- http://lobid.org/resource/HT014215912
- http://lobid.org/resource/HT015414894
- http://lobid.org/resource/HT016608165
- http://lobid.org/resource/HT018131501
- http://lobid.org/resource/HT018312899

There is one resource in the test set where `lv:containedIn` should NOT occur although it currently does: http://lobid.org/resource/BT000003404 which is typed as `bibo:Article` though it actually is a map. This resource obviously has some more problems and we will have to look further into it.

**Comment by acka47** [comment]
> http://lobid.org/resource/BT000003404 which is typed as `bibo:Article` though it actually is a map

The information is there we use `bibo:Map` with `dct:medium`. But there is no data in field 599 so that containedIn shouldn't be there.

**Comment by dr0i** [comment]
There is no 'lv:containedIn' for BT000003404  but 'lv:volumeIn' which comes from field '001-2a', see .https://github.com/lobid/lodmill/commit/783ce3b303d4b415866802ad3a32cc6c44cbfa57.

**Comment by acka47** [comment]
> There is no `lv:containedIn` for BT000003404  but `lv:volumeIn` which comes from field `001-2a`, see .https://github.com/lobid/lodmill/commit/783ce3b303d4b415866802ad3a32cc6c44cbfa57.

No, there is. See https://github.com/lobid/lodmill/blob/e8a1a2c11edc866b1fc71435e002a86ace7a4d2c/lodmill-rd/src/test/resources/hbz01.nt#L1664

**Comment by dr0i** [comment]
Ah, I see, these are only in the junit test set, not on staging (anymore - index was switched because of parallel transformation work).
And now I remember [my own comment](https://github.com/lobid/lodmill/issues/702#issuecomment-132236981) what I wanted to know:
Indeed I did this not only for articles but for every resource which is part of something.
Will adjust this.

**Comment by dr0i** [comment]
Btw, a more intuitive naming of the lv property would then be: `lv:articleContainedIn`.

**Comment by acka47** [comment]
> Btw, a more intuitive naming of the lv property would then be: `lv:articleContainedIn`.

Maybe, but you shouldn't trust property names anyway. The vocab is quite clear I'd say:

```
lv:containedIn
   rdf:type owl:ObjectProperty ;
   rdfs:label "Contained in"@en ; 
   rdfs:label "Enthalten in"@de ;
   rdfs:isDefinedBy <http://purl.org/lobid/lv> ;
   rdfs:comment "This property is used to link an article to a journal or an edited volume it is contained in."@en ;
   rdfs:comment "Diese Property verlinkt einen Artikel mit einer Zeitschrift oder einer Aufsatzsammlung, in der er enthalten ist."@de;
   rdfs:subPropertyOf dct:isPartOf;
   rdfs:domain bibo:Article ;
   rdfs:range dct:BibliographicResource .
```

**Comment by dr0i** [comment]
Sure, but then a arbitrary name like 'lv:jbkjkj' would be less misleading.

**Comment by acka47** [comment]
@dr0i  FWIW, as the property will only appear on articles, there isn't anything misleading. And if people want to reuse it with their data, they have to take a look at the vocabulary anyway.

Following your argument, we should also rename:
- `contributor` to `contributorToTheBibliographicResource`
- `placeOfPublication` to `placeOfPublicationOfTheBibliographicResource`
- `owner` to `ownerOfTheItem`
- etc.

I assume you don't want this, do you?

**Comment by dr0i** [comment]
No, but I would suggest renaming it if `owner` would e.g. solely  mean `owner of an article`.
Anyway, u r right naming is just "Schall und Rauch", thervor ... kjlkj ;)

**Comment by dr0i** [comment]
@acka47 is the diff in the tests enough for you to evaluate the commits?

**Comment by acka47** [comment]
I already did it on this basis. Anyway, you shouldn't directly deploy to production when I give a "+1". I will have to look at the whole set on staging first.

**Comment by dr0i** [comment]
Ack. Have you had a look at the last commit?

**Comment by acka47** [comment]
Looks good now. +1

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
