### ISSUE TITLE
Remove alternative title from volumes

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#711]
Currently, volumes don't have a title (see #498 ) but many have `otherTitleInformation` from field 331 resp. 333 (see [current morph, lines 473-475](https://github.com/lobid/lodmill/blob/9ce9052c069d6cc77965dfc60c066bc7321225fc/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L473-L475). This actually is the additional title information from the superordinated resource and, thus, should be removed from the volumes.

Example http://lobid.org/resource/HT017261040/about (snippet):

```javascript

{
    "@id" : "http://lobid.org/resource/HT017261040",
    "@type" : [ "http://purl.org/dc/terms/BibliographicResource", "http://purl.org/ontology/bibo/Book" ],
    "otherTitleInformation" : "deutschsprachige Fotobücher 1918 bis 1945"
}
```

[Source](http://beta.lobid.org/hbz01/HT017261040):

```xml
<datafield tag="331" ind1="-" ind2="2">
  <subfield code="a">Autopsie</subfield>
</datafield>
<datafield tag="335" ind1="-" ind2="2">
  <subfield code="a">deutschsprachige Fotobücher 1918 bis 1945</subfield>
</datafield>
```

**Comment by dr0i** [comment]
Deployed to staging. Mind that #498 volumes now _have_  a title.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
