### ISSUE TITLE
Creators with roles should be represented as such

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#715]
Example: http://lobid.org/resource/HT014525099

[Source](http://lobid.org/resource?id=HT014525099&format=source) (snippet):

``` xml
<datafield tag="120" ind1="e" ind2="1">
  <subfield code="p">Rotzsch, Hans-Joachim</subfield>
  <subfield code="d">1929-2013</subfield>
  <subfield code="b">[Dir.]</subfield>
  <subfield code="9">(DE-588)118867539</subfield>
</datafield>
```

With the current solution (now on staging), we will only have this one as `dct:creator` and not as `marcrel:cnd`, although "[Dir]" is mapped to this relator code in the morph, see [lines 859-862 of current morph](https://github.com/lobid/lodmill/blob/c784ffce86e71bd664f8f3a654c51073cfdc38ec/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L859-L862).

The goal should be – as discussed in the DINI KIM "Titeldaten" group – to have this person in the RDF as creator AND cnd:

``` javascript
{
  "@graph" : [  {
    "@id" : "http://d-nb.info/gnd/118867539",
    "preferredName" : "Rotzsch, Hans-Joachim, 1929-2013",
    "preferredNameForThePerson" : "Rotzsch, Hans-Joachim, 1929-2013"
  }, {
    "@id" : "http://test.lobid.org/resource/HT014525099",
    "extent" : "2 Schallpl. : 33 UpM, stereo ; 30 cm",
    "creator" : [ "http://d-nb.info/gnd/129389641", "http://d-nb.info/gnd/11850553X", "http://d-nb.info/gnd/118500546", "http://d-nb.info/gnd/118867539" ],
    "conductor": "http://d-nb.info/gnd/118867539" 
   }
  ]
}
```

**Comment by dr0i** [comment]
For now we use metamorph-`choose` so that we indeed will only have exactly _one_ role.

**Comment by acka47** [comment]
The former me wasn't right writing down this issue. As the person in question is catalogued under 120, indicator1=e we are dealing with a "Interpret", see [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile):

```
104       NAME DER 2. PERSON IN ANSETZUNGSFORM

          Indikator:
          a = Name des 2. Verfassers
              zweiteilige Nebeneintragung
          b = Name der 2. sonstigen beteiligten Person
              einteilige Nebeneintragung
          c = Name der 2. sonstigen beteiligten Person
              ein- und zweiteilige Nebeneintragung
          f = Name der 2. gefeierten Person
              zweiteilige Nebeneintragung mit dem Formalsachtitel
              'Festschrift'
          e = Name des 2. Interpreten
              einteilige Nebeneintragung
```

"Interpret" != creator. From the [MARC relators list](http://id.loc.gov/vocabulary/relators.html) [performer](http://id.loc.gov/vocabulary/relators/prf) seems the right thing to use – if no specific role like "conductor" is given. The definition of "performer" role:

> A person contributing to a resource by performing music, acting, dancing, speaking, etc., often in a musical or dramatic presentation, etc. If specific codes are used, [prf] is used for a person whose principal skill is not known or specified

Thus, we can close this issue and open another one that deals with correctly handling the indicator e persons as performer.

**Comment by dr0i** [comment]
This issue is rejected, hbz/lobid-resources#150 is created instead.
Closing.
