### ISSUE TITLE
Type resources with GND subject "Aufsatzsammung" as EditedVolume

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#716]
Obviously, we only type resources with non-GND subject as `lv:EditedVolume`. There also exists a GND subject "Aufsatzsammlung": http://d-nb.info/gnd/4143413-4

Look for example at the NWBib:
- There are 269 resources with this GND subject, see http://lobid.org/nwbib/search?q=*&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4143413-4
- Only six of these are typed as EditedVolume, see http://lobid.org/nwbib/search?q=*&subject=http%3A%2F%2Fd-nb.info%2Fgnd%2F4143413-4&t=http%3A%2F%2Fpurl.org%2Flobid%2Flv%23EditedVolume

We will have to add the GND subject to [line 1116 of the current morph](https://github.com/lobid/lodmill/blob/c784ffce86e71bd664f8f3a654c51073cfdc38ec/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L1116).

**Comment by dr0i** [comment]
Deployed to staging.
Note that the second URL brings up 251 , not 269. Why this is so, I don't know.

**Comment by acka47** [comment]
> Note that the second URL brings up 251 , not 269. Why this is so, I don't know.
I don't understand why. Anyway, we have significantly more edited volumes typed as such which is good. 

 +1

**Comment by dr0i** [comment]
Deployed to production, cloing.
