### ISSUE TITLE
Remove past publisher(s) and publication place(s)

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#717]
Example: http://lobid.org/resource/ZDB613412-9/about

**Comment by acka47** [comment]
We may also just leave out the information on past publishers and places as this isn't actually needed.

**Comment by acka47** [comment]
> We may also just leave out the information on past publishers and places as this isn't actually needed.

Yes, we will do it like this. The ZDB does the same with their RDF, see `rapper -o turtle http://ld.zdb-services.de/resource/613412-9`. 

The current publisher and place can be found in `410` and `412` as well as – if there are two publishers – in `415` and `417`. From the [MAB documentation](http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/mabTitelBibliographischeDaten2001.txt?__blob=publicationFile):

```
410       ORT(E) DES 1. VERLEGERS, DRUCKERS USW.

          Indikator:
          blank = Verlagsort(e)
          a     = Druckort(e)
          b     = Vertriebsort(e)
          c     = Auslieferungsort(e)
          u     = nicht spezifiziert

412       NAME DES 1. VERLEGERS, DRUCKERS USW.

          Indikator:
          blank = Verleger
          a     = Drucker
          b     = Vertrieb
          c     = Auslieferer
          u     = nicht spezifiziert

415       ORT(E) DES 2. VERLEGERS, DRUCKERS USW.
416       ADRESSE DES 2. VERLEGERS, DRUCKERS USW.
417       NAME DES 2. VERLEGERS, DRUCKERS USW.
```

For the example http://lobid.org/resource/ZDB613412-9/about, the source looks like this:

```xml
<datafield ind2="1" ind1="-" tag="410">
  <subfield code="a">Krefeld</subfield>
</datafield>
<datafield ind2="1" ind1="-" tag="412">
  <subfield code="a">Kronsbein</subfield>
</datafield>
<datafield ind2="1" ind1="-" tag="418">
  <subfield code="a">JÃ¼chen-Wallrath</subfield>
  <subfield code="g">Verl. Zenk</subfield>
  <subfield code="h">-1987</subfield>
</datafield>
<datafield ind2="1" ind1="-" tag="418">
  <subfield code="a">KÃ¶ln</subfield>
  <subfield code="g">Kleikamp</subfield>
  <subfield code="h">1988-1995</subfield>
</datafield>
<datafield ind2="1" ind1="-" tag="418">
  <subfield code="a">Dormagen</subfield>
  <subfield code="g">Verl. Wegener</subfield>
  <subfield code="h">1996;2001</subfield>
</datafield>
```
Following the above, field `418` "ANGABEN ZU WEITEREN UND/ODER FRUEHEREN VERLEGERN, DRUCKERN ETC." should be removed from the transformation/morph.

**Comment by acka47** [comment]
@dr0i I will give it a try adjusting the moprh myself.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
