### ISSUE TITLE
inSeries relation not transformed correctly

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#718]
Customer feedback from today:

> die Titel
http://lobid.org/nwbib/HT018290299
http://lobid.org/nwbib/HT017500124
http://lobid.org/nwbib/HT018483380
sind in zwei Reihen erschienen. Die zweite Schriftenreihe wird in der neuen NWBib gar nicht genannt und die Bandzählung der zweiten Reihe (?) als unverständliche Zeichenfolge (?)

While `isPartOf` link from these resources to http://lobid.org/resource/HT017500108 exists it isn't represented as `inSeries` relation, rather  for the relation only a blank node with a type exists. The data is in field 463:

```xml
datafield ind2="1" ind1="-" tag="463">
    <subfield code="a">HT017500108</subfield>
</datafield> 
```

Currently it looks – for example – like this:

```javascript
{ "@graph": [ {
    "@id" : "_:t4553",
    "@type" : "http://purl.org/lobid/lv#SeriesRelation"
  }, {
    "@id" : "_:t4554",
    "@type" : "http://purl.org/lobid/lv#SeriesRelation",
    "numbering" : "19",
    "series" : "http://lobid.org/resource/HT006514951"
  },
   "@id" : "http://lobid.org/resource/HT018290299",
    "inSeries" : [ "_:t4553", "_:t4554" ]
  } ]
}
```

**Comment by dr0i** [comment]
It's an repeatable field but wasn't configured as such.
Deployed to small test. try `curl "http://quaoar1.hbz-nrw.de:9200/lobid-resources-staging/json-ld-lobid/http:%2F%2Flobid.org%2Fresource%2FHT018290299" | json_pp`.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1 

@fsteeg There is a problem in NWBIb, though. See the examples http://test.lobid.org/nwbib/HT018290299, http://test.lobid.org/nwbib/HT017500124, http://test.lobid.org/nwbib/HT018483380. Two volume numbers are associated with only one link, the other link to a super-ordinated resource is not shown. We will hae to adjust this so that the links to series and multi-volume work are displayed separately with the associated volume number.. Will make an issue for this as soon as this one is deployed to production.

**Comment by dr0i** [comment]
Deployed to production, closing.
