### ISSUE TITLE
Only have dateRange value for "issued" 

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#726]
As reported by NWBib stakeholders (Mail by E. Lakomy from 2015-09-28).

Example http://lobid.org/resource/HT001387709 currently looks like this (snippet):

```javascript
{
  "@graph" : [ {
    "@id" : "http://lobid.org/resource/HT001387709",
    "@type" : [ "http://purl.org/dc/terms/BibliographicResource", "http://purl.org/ontology/bibo/Newspaper" ],
    "issued" : [ "1946", "1946 - " ],
   } ]
}
```

The value without the hypen (`1946`) should be removed and only `1946-` retained. As far as I can see from the [current morph, lines 545-560](https://github.com/lobid/lodmill/blob/7bf95a860ef14058ec8d24771b10016e7a8fa6a3/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L545-L560), the data stems from the same field (425b). From the source:

```xml
<datafield ind2="1" ind1="b" tag="425">
  <subfield code="a">1946</subfield>
</datafield>
```

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
