### ISSUE TITLE
Use colon instead comma when generating volume titles

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#728]
As of https://github.com/lobid/lodmill/issues/498#issuecomment-142002257, we decided for a comma. NWBib stakeholders suggested using a colon which wouldn't break anything I believe and would indead make this easier to understand. I will adjust the morph accordingly.

**Comment by dr0i** [comment]
See e.g. http://lobid.org/resource/BT000003404.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
I see two semicolons in this example: "Deutschland ; 2 ; Nordrhein-Westfalen, Niedersachsen-Süd". The first semicolon should stay a comm, though, and the second be a colon. Also, i would remove the spaces before colon and comma, resulting in this: "Deutschland, 2: Nordrhein-Westfalen, Niedersachsen-Süd"

**Comment by acka47** [comment]
Sorry, I should have added the actual stakeholder request in the issue. Here it is (mail by U. Pflughaupt from 2015-09-29):

> B: Bandangaben bei TA von Bänden mit und ohne Bandtitel im Titel z.B. http://lobid.org/nwbib/HT018486420
z.Z.
Oberhausen , 4 , Oberhausen in Wirtschaftswunder und Strukturwandel
Besser?
Oberhausen , 4: Oberhausen in Wirtschaftswunder und Strukturwandel
Ein Doppelpunkt würde deutlicher machen, dass der Bd. 4 diesen Titel hat. Ansonsten finde ich es nicht schlimm, dass die Überordnung oben und unten in der TA des 4. Bandes genannt wird.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
Better, but still not as expected. Please deploy on production and add th spaces _after_ comma and colon so that it looks like this: `"Deutschland, 2: Nordrhein-Westfalen, Niedersachsen-Süd"`

**Comment by dr0i** [comment]
Deployed to staging, see e.g. http://test.lobid.org/resource/HT001898812/about.

**Comment by dr0i** [comment]
Hm. Something went wrong, commits are not reflected. Will look into it.

**Comment by dr0i** [comment]
Everything is fine, just tested against the wrong index alias.
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
