### ISSUE TITLE
Include links to abstracts in RDF 

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#729]
Requested by NWBib stakeholders on 2015-09-29 (mail by U. Pflughaupt):

> z.B. http://lobid.org/nwbib/HT018198218 http://lobid.org/nwbib/HT018705251
Wenn man die Titel in der alten NWBib aufruft, sieht man jeweils noch den Link auf die Inhaltsangabe mit einem zusammenfassenden Text, der in der neuen NWBib fehlt.

For the example http://lobid.org/resource/HT018705251 the source looks like this:

```xml
<datafield ind2="1" ind1="e" tag="655">
            <subfield code="m">X:MVB</subfield>
            <subfield code="q">text/html</subfield>
            <subfield code="u">
              http://deposit.d-nb.de/cgi-bin/dokserv?id=5127371&amp;prov=M&amp;dok_var=1&amp;dok_ext=htm
            </subfield>
            <subfield code="3">Inhaltstext</subfield>
            <subfield code="A">2</subfield>
          </datafield>
```

For http://lobid.org/resource/HT018198218 like this:

```xml
 <datafield ind2="1" ind1="e" tag="655">
            <subfield code="m">X:MVB</subfield>
            <subfield code="q">text/html</subfield>
            <subfield code="u">
              http://deposit.d-nb.de/cgi-bin/dokserv?id=4527181&amp;prov=M&amp;dok_var=1&amp;dok_ext=htm
            </subfield>
            <subfield code="3">Inhaltstext</subfield>
            <subfield code="A">2</subfield>
          </datafield>
```

**Comment by acka47** [comment]
We will use `http://purl.org/dc/terms/description` for this. As its range is not defined as string this is no problem. We won't use `dct:absctract` as the link often goes to the "Klappentext" of the resource which not necessary is a summary...

Note that we will have to add `dct:description` to the JSON-LD context.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to staging, not forgetting the json-ld context.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production,closing.
