### ISSUE TITLE
Set up monitoring for indexing errors

### ISSUE THREAD

**Issue by fsteeg** [lobid/lodmill#73]
With some N-Triples, the resulting JSON-LD causes errors when indexed in Elasticsearch (e.g. `http://lobid.org/vocab/lobid#fulltextOnline` links that don't contain valid URLs). Since new data will be indexed automatically, we need some monitoring solution that alerts us about such issues in the input data.

**Comment by acka47** [comment]
Won't fix this for API 1.0, I hope we have this covered for 2.0, though... Closing.
