### ISSUE TITLE
Differentiate publication statement of original and secondary form (e.g. digitized version)

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#730]
Currently, we both have the issue date of the original and the secondary form grouped under the same property (`issued`). We will need to separate these.

Example http://lobid.org/resource/CT003012479 (snippet):

``` javascript
{
  "@graph" : [ {
    "@id" : "http://lobid.org/resource/CT003012479",
    "@type" : [ "http://purl.org/dc/terms/BibliographicResource", "http://purl.org/lobid/lv#Miscellaneous" ],
    "issued" : [ "1805", "2015" ]
    } ]
}
```

From the source (snippet):

``` xml
<datafield ind2="1" ind1="a" tag="425">
  <subfield code="a">1805</subfield>
</datafield>
<datafield ind2="1" ind1="a" tag="619">
  <subfield code="a">2015</subfield>
</datafield>
```

**Comment by acka47** [comment]
I would put the date of the original resource into `issued` and look for another property for the issue date of the secondary form. Though this is strictly speaking not correct as the record actually describes the digitized version it makes most sense e.g. for a publication date filter. I will ask which solution NWBib stakeholders prefer.

**Comment by acka47** [comment]
This is the solution NWBib editors agree on (mail by E. Lakomy from 2015-10-09 which was agreed on by U. pflughaupt on 2015-10-13):

> wir meinen, in der CT-Aufnahme sollten beide Erscheinungsjahre, also von  der Primär- als auch von der Sekundärform angezeigt werden.  Sie sollten dann entsprechend beim passenden Verlag und  Verlagsort stehen, wie Frau Pflughaupt bereits geschrieben hat. .D. h. wie auch im VK würden sowohl das Impressum des Originals als auch das des Digitalisats in der CT-Aufnahme  erscheinen CT003001322.

> Zur Facettierung würden wir das EJ des Originals vorziehen,  da es  unseres Erachtens den Benutzer vermutlich nicht interessiert, wann das Digitalisat entstanden ist. Ihm geht es wohl um das Erscheinungsjahr des Originals, insbesondere wenn es sich  um historische Sachverhalte handelt.
Außerdem wird in der alten NWBib bei einer Trefferliste von Parallelausgaben ebenfalls das EJ des Originals zugrunde gelegt.  Beispiel „Digitalisierungsstrategie der Universitätsbibliotheken Nordrhein-Westfalens“. Hier haben CT und HT Aufnahme beide das EJ 2009.

> Im VK kann man bei einer Trefferliste von Parallelausgaben sofort erkennen, welche der beiden Titel die eRessouce ist. Dieser Titel ist mit einem sprechenden Icon und dem Zusatz „Elektronische Ressource“  versehen. Wir finden diese Anzeige recht übersichtlich und würden uns das für die Trefferliste in der neuen NWBib ebenfalls wünschen http://lobid.org/nwbib/search?location=&q=digitalisierungsstrategie+westfalens. 
Könnte man bei dieser Trefferliste hier beispielsweise zum Icon Publikationstyp „Buch“ eventuell die Medienart „Online“ hinzufügen? Oder ebenfalls im Titel [Elektronische Ressource] ergänzen?

**Comment by acka47** [comment]
With https://github.com/lobid/lodmill/commit/1fda4d0ddec96ae45c0311d6581efd4fb665287e we have removed the publication data for secondary forms from he RDF. First and foremost, we will have to re-introduce it into the data to meet stakeholder requirements.

**Comment by acka47** [comment]
I guess the requirement to associate respective publication place, publisher and publication date can only be accomplished by introducing a "publication event" blank node to our data model. We should think about it latest in the context of [API 2.0](https://github.com/hbz/lobid/issues/1).

Regarding the given [example](http://lobid.org/resource/CT003012479), the JSON-LD could look something like this (using the [British Library's data model](http://www.bl.uk/bibliographic/pdfs/bldatamodelbook.pdf)):

```javascript
{
	"@context": {
		"@vocab": "http://www.bl.uk/schemas/bibliographic/blterms",
		"time": "http://purl.org/NET/c4dm/event.owl#time",
		"place": "http://purl.org/NET/c4dm/event.owl#place",
		"agent": "http://purl.org/NET/c4dm/event.owl#agent",
		"comment": "http://www.w3.org/2000/01/rdf-schema#comment"
	},
	"@id" : "http://lobid.org/resource/CT003012479",
	"publication": [ {
		"@type": "PublicationEvent",
		"time": "1805",
		"place": "Düsseldorf",
		"agent": "Bögemann"
		}, {
		"@type": "PublicationEvent",
		"time": "2015",
		"place": "Düsseldorf",
		"agent": "Universitäts- und Landesbibliothek",
		"comment": "Digitalisierte Ausg."
		}
	]
}
```

The relevant parts of the source data look like this: 

```xml
<datafield tag="410" ind1="-" ind2="1">
	<subfield code="a">[Düsseldorf]</subfield>
</datafield>
<datafield tag="412" ind1="-" ind2="1">
	<subfield code="a">Bögemann</subfield>
</datafield>
<datafield tag="425" ind1="a" ind2="1">
	<subfield code="a">1805</subfield>
</datafield>
<datafield tag="610" ind1="-" ind2="1">
	<subfield code="a">Digitalisierte Ausg.</subfield>
</datafield>
<datafield tag="611" ind1="a" ind2="1">
	<subfield code="a">Düsseldorf</subfield>
</datafield>
<datafield tag="613" ind1="a" ind2="1">
	<subfield code="a">Universitäts- und Landesbibliothek</subfield>
</datafield>
<datafield tag="619" ind1="a" ind2="1">
	<subfield code="a">2015</subfield>
</datafield>
```

**Comment by acka47** [comment]
Discussing this offline with @fsteeg he made clear that this structure would make more sense for working with elasticsearch:

```javascript
{
	"@context": {
		"@vocab": "http://www.bl.uk/schemas/bibliographic/blterms",
		"time": "http://purl.org/NET/c4dm/event.owl#time",
		"place": "http://purl.org/NET/c4dm/event.owl#place",
		"agent": "http://purl.org/NET/c4dm/event.owl#agent",
		"comment": "http://www.w3.org/2000/01/rdf-schema#comment",
		"primaryPublication": "http://purl.org/lobid/lv#primaryPublication",
 		"secondaryPublication": "http://purl.org/lobid/lv#secondaryPublication"
	},
	"@id" : "http://lobid.org/resource/CT003012479",
	"publication": {
		"primaryPublication": { 
			"@type": "PublicationEvent",
			"time": "1805",
			"place": "Düsseldorf",
			"agent": "Bögemann"
			}, 
		"secondaryPublication": {
			"@type": "PublicationEvent",
			"time": "2015",
			"place": "Düsseldorf",
			"agent": "Universitäts- und Landesbibliothek",
			"comment": "Digitalisierte Ausg."
			}
	}
}
```

**Comment by acka47** [comment]
@fsteeg I wonder whether it would be important to have the same structure all over the data, i.e. whehter we would use publication.primaryPublication for resources that only have one publication statement or whether we could skip the `primaryPublication` in this case.

**Comment by fsteeg** [comment]
Yes, we should always have the same structure if we do it this way (both for queries and result processing).

**Comment by acka47** [comment]
The structure from https://github.com/lobid/lodmill/issues/730#issuecomment-154338839 adds more complexity than needed. A far better and straightforward approach is the one outlined below.

Rather than utilizing the previously mentiond BL data model, we will use schema.org, though. The PublicationEvent approach is also used in schema.org but it is used with literals for publisher and place instead of entities as in the [BL approach](http://www.bl.uk/bibliographic/pdfs/bldatamodelbook.pdf). As we only have literals we can avoid bnodes with schema.org.

First, a version with full URIs / without `@context` to make implementation easier for @dr0i to understand:

```javascript
{
	"@id" : "http://lobid.org/resource/CT003012479",
	"http://schema.org/publication": { 
		"@type": "http://schema.org/Publication",
		"http://schema.org/startDate": "1805",
		"http://schema.org/location": "Düsseldorf",
		"http://schema.org/publishedBy": "Bögemann"
		}, 
	"http://purl.org/lobid/lv#secondaryPublication": {
		"@type": "http://schema.org/Publication",
		"http://schema.org/startDate": "2015",
		"http://schema.org/location": "Düsseldorf",
		"http://schema.org/publishedBy": "Universitäts- und Landesbibliothek",
		"http://purl.org/dc/terms/description": "Digitalisierte Ausg."
		}
}
```

This is what it will look like in ES with `@context` information:

```javascript
{
	"@id" : "http://lobid.org/resource/CT003012479",
	"publication": { 
		"@type": "http://schema.org/Publication",
		"startDate": "1805",
		"location": "Düsseldorf",
		"publishedBy": "Bögemann"
		}, 
	"secondaryPublication": {
		"@type": "http://schema.org/Publication",
		"startDate": "2015",
		"location": "Düsseldorf",
		"publishedBy": "Universitäts- und Landesbibliothek",
		"description": "Digitalisierte Ausg."
		}
}
``` 

Except `description` (whose `@context` entry currently is incorrect as I just [saw](https://github.com/hbz/lobid/pull/268)), we will have to add all properties to the JSON-LD context.

**Comment by acka47** [comment]
We need to do this before launching API 2.0. Assigning myself to see whether Bibframe or something else provides the necessary RDF properties to express this.

**Comment by dr0i** [comment]
I found a note in the morph:
`
`
Maybe @acka47 can say something about that?

**Comment by dr0i** [comment]
There is another note in the morph:
`<!-- TODO if multiple publisher these are melted to one. See HT015082724-->`
Think this is about the issue of the superordinated resource? Should we just ignore this?

And another note:
`
<combine name="@dateSecondary" value="${dateSecondary}">
<data source="021[-b]1.a"/>
<data source="619[ab][-1].a" `
Don't get it, especially when looking at HT017411546 which doesn't have `field 021` but an issue date of the secondary form.
(will remove the comment and the mandatory `021` field.)

**Comment by dr0i** [comment]
I gather we can get rid of redundant properties if this is implemented, right? That is, removing:
- [X] publicationStatement
- [X] publisher
- [X] placeOfPublication
- [X] issued
