### ISSUE TITLE
Provide full base dump of ntriples to ckan

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#734]
Customer asked about an update of the base dump hosted at ckan.
In fact, the data was not as outdated as the desription site on ckan proclaimed ("2012", while in fact the data was created at "2015-04"), so only the ckan-metadata needs an update. However, I wasn't able to do this so I opened an issue, see http://help.datahub.io/discussions/questions/1505-how-to-update-the-additional-information.

Meanwhile: a new full dump was created using the `scroll` parameter of the API. This was possible by assigning 48GB of RAM to the Play instance to avoid the memory issue. Don't know exactly what amount of RAM would be enough, it seems to took 21% of 82GB, so around 20GB should be good.

Time needed: ~7h
Records in it: >19M
Size of file: ~8GB
Serialisation: ntriples

**Comment by acka47** [comment]
Closing
