### ISSUE TITLE
Add mapping for [Red.] to marcrel:red

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#736]
Currently, we don't have a mapping to MARC relator codes for occirences of `[Red.]` or similar. Thus, person with this role indicator are mapped to dct:contributor. Instead `marcrel:red` should be used.

Example: http://lobid.org/resource/HT018309120/about

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
Now the person now is `redaktor` (which is good) _but also_ `contrinutor`. By now, we only have the persons with one role, thus, the `contributor` must be removed.

**Comment by acka47** [comment]
I adjusted this, see https://github.com/lobid/lodmill/commit/be601139e7df4ab91058ee5c238dc433f1009367.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
@jschnasse As this originated from requirements by publisso customers: Can you also take a short look at this as?

**Comment by jschnasse** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
