### ISSUE TITLE
Creators missing in RDF

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#741]
See e.g. http://lobid.org/resource/HT018768468/about where this data from the source isn't transformed to the RDF:

```xml
 <datafield ind2="2" ind1="-" tag="100">
            <subfield code="p">Capellaro, Marcus</subfield>
            <subfield code="9">(DE-588)1077065299</subfield>
</datafield>
<datafield ind2="2" ind1="a" tag="104">
            <subfield code="p">Sturm, Diethard</subfield>
            <subfield code="d">1944-</subfield>
            <subfield code="9">(DE-588)110756045</subfield>
</datafield>
```

`ind2="2"` indicates that this is enriched from the superordinated resource. It should be in tha data in lobid to prevent the "Schiller-Räuber-Problem".

**Comment by acka47** [comment]
Files from test with `tag="100" ind1="-" ind2="2"`: HT015891797 & HT017529028.

**Comment by dr0i** [comment]
Within the domain of `creator` comes also often `rdvocab:statementOfResponsibility`. In your example of /HT018768468 this would be `by Marcus Capellaro ; Diethard Sturm. Under contribution of Patricia Sadre Dadras ...`. You like that?

**Comment by acka47** [comment]
>  In your example of /HT018768468 this would be `by Marcus Capellaro ; Diethard Sturm. Under contribution of Patricia Sadre Dadras ...`. You like that?

I don't think it is incorrect to also add it to the subordinated rsources. So please inlcude.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
I f I remember correctly, this was reported by @jschnasse . Jan, perhaps you better also take a look at it before deploying to production...

**Comment by jschnasse** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
