### ISSUE TITLE
Two preferred names for one event

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#742]
See http://lobid.org/resource/HT018771475/about where you can find:

```javascript
{
    "@id" : "http://d-nb.info/gnd/1074109953",
    "preferredName" : [ "7. Schloss Bensberg Classics, 2015, Bergisch Gladbach", "7., 2015, Bergisch Gladbach" ],
    "preferredNameForThePerson" : "7. Schloss Bensberg Classics, 2015, Bergisch Gladbach"
  }
```

As a result, NWBib looks broken, see http://lobid.org/nwbib/HT018771475. 

This probably was introduced with #740.

**Comment by dr0i** [comment]
A data sample already existing within our unit test data is http://lobid.org/resource/HT014319164.

**Comment by acka47** [comment]
Yes, both in http://lobid.org/nwbib/HT018771475 and http://lobid.org/resource/HT014319164 a GND resource is both creator and subject.

**Comment by acka47** [comment]
I propose to leave out the birth date in `preferedName` for GND resources refered to twice in a record.

**Comment by dr0i** [comment]
See hbz/lobid#244 where I said to only remove the birth date from creator/contributor , NOT subjects. With the upcoming commit this will be changed so that also gnd subject will not have a birth date.

**Comment by dr0i** [comment]
It should be easy when `9??` (aka subject-chains) could be treated like `1??` (aka persons), but they couldn't because using person we disconfigured the date (subfield `d`), while this field is desired when dealing not with persons (like here `2015`, the year of the event).

**Comment by dr0i** [comment]
Deployed test set to staging. Please @acka47 have a look and ping if this is fine to deploy the whole data to staging.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
