### ISSUE TITLE
Transform field 520 in RDA records

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#746]
Sub-issue of https://github.com/hbz/lobid/issues/161. In RDA records, the "Hochschulschriftenvermerk"/thesis information is catalogued in field 520. We will need to map this field to `thesisInformation`.

I don't know whether an example exists. @droi, can you generate one Aleph XML file from https://github.com/hbz/lobid/files/18519/rda-ids.txt so that I can run grep on it to look for 520 or other fields in the future?

**Comment by acka47** [comment]
Thanks @dr0i for providing the file, see https://github.com/hbz/lobid/issues/161#issuecomment-153293572. I found the following examples including `520`:
- http://lobid.org/resource/HT018770176
- http://lobid.org/resource/HT018782467
- http://lobid.org/resource/HT018785797

**Comment by acka47** [comment]
Looking at the Aleph XML and the existing `thesisInformation` literals, we should for now just concatenate the three subfields of 520 in the order "c, b, d" to get a result similar to the existing thesis information. From the examples in https://github.com/hbz/lobid/issues/166, I get the following order in field `thesisInformation`: place, institution, thesis type, year (Examples: "Bamberg, Univ., Magisterarb., ca. 1994", "Magdeburg, Univ., Habil.-Schr., 1997", "Zugl., Göttingen, Univ., Diss., 2013")

From http://lobid.org/resource/HT018770176 (snippet):

```xml
<datafield ind2="1" ind1="-" tag="520">
  <subfield code="b">Dissertation</subfield>
  <subfield code="c">Albert-Ludwigs-Universität Freiburg</subfield>
  <subfield code="d">2014/2015</subfield>
</datafield>
```

Expected outcome (snippet):

```javascript
{
    "@id" : "http://lobid.org/resource/HT018770176",
    "thesisInformation": "Albert-Ludwigs-Universität Freiburg, Dissertation, 2014/2015"
}
```

From http://lobid.org/resource/HT018782467 (snippet):

```xml
<datafield ind2="1" ind1="-" tag="520">
   <subfield code="b">Dissertation</subfield>
   <subfield code="c">Karl-Franzens-Universität Graz</subfield>
   <subfield code="d">2012</subfield>
</datafield>
```

Expected outcome:

```javascript
{
    "@id" : "http://lobid.org/resource/HT018782467",
    "thesisInformation": "Karl-Franzens-Universität Graz, Dissertation, 2012"
}
```

From http://lobid.org/resource/HT018785797 (snippet):

```xml
<datafield ind2="1" ind1="-" tag="520">
  <subfield code="b">Dissertation</subfield>
  <subfield code="c">Pontificia Università Gregoriana</subfield>
  <subfield code="d">2015</subfield>
</datafield>
```

Expected outcome:

```javascript
{
    "@id" : "http://lobid.org/resource/HT018785797",
    "thesisInformation": Pontificia Università Gregoriana, Dissertation, 2015"
}
```

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
