### ISSUE TITLE
Indicate type of GND resource in /resource RDF

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#750]
Reported by W. Greßhof on 2015-08-26. (Obviously, this issue is overdue. Sorry.)

Since hbz/lobid#139  one cannot always and reliable see from the lobid /resource data what types of GND resources (DifferentiatedPerson, PlaceOrGeographicName, SubjectHeading etc.) are referenced. Example http://lobid.org/resource/HT012778132/about (snippet):

```javascript
{
    "@id" : "http://d-nb.info/gnd/189528982",
    "preferredName" : "Houben, Thomas"
  }
```

One cannot see that this is a person. The most elegant solution would be by adding the type to each GND resource. In this case:

```javascript
{
    "@id" : "http://d-nb.info/gnd/189528982",
    "@type": "http://d-nb.info/standards/elementset/gnd#DifferentiatedPerson",
    "preferredName" : "Houben, Thomas"
  }
```

As far as I can remember that results in other problems so that we can't do this.

Thus, the only solution would be the one we had before #669: Reliably adding the sub-property of `gnd:preferredName`. E.g.:

```javascript
{
    "@id" : "http://d-nb.info/gnd/189528982",
    "preferredNameForThePerson": "Houben, Thomas",
    "preferredName" : "Houben, Thomas"
  }
```

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1 But to be really reliable we need to remove duplicate preferredName properties. See https://github.com/hbz/lobid/issues/144#issuecomment-105980315 (which we might reopen).

**Comment by dr0i** [comment]
Deployed to production. Will reopen hbz/lobid#144. Closing this one.
