### ISSUE TITLE
Take into account MAB field 501 in transformation to RDF

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#756]
Required by publisso stakeholders.

E.g. http://lobid.org/resource/HT018362113 (snippet):

```xml
<datafield tag="501" ind1="-"  ind2="1">
  <subfield code="a">
              Dokument ist gesperrt, neue Version unter urn:nbn:de:hbz:38m-0000009024
  </subfield>
</datafield>
```

**Comment by acka47** [comment]
Wondering what is written down in 501 in other records, I took a look at some. Here are the – non-representative – results:

"Literaturangaben", "Übers. des Hauptsacht.: Wohin geht die chinesische Wirtschaft?", ">Organon ist ein alter Sammeltitel für die Logischen Schriften: Categoriae. - De interpretatione. - Analytica priora. - Analytica posteriora. - Topica. - De sophisticis elenchis", "Repr.: Amsterdam : Rodopi", "Literaturverz. S. 82 - 85", ">Bibliography: p235-253. - Includes index", "Kopie", "Literaturverz. S. 96 - 103", "Literaturverz. S. 318 - 332", "Repr. 1989: Bad Feilnbach : Schmidt Periodicals", "Systemvoraussetzungen: Windows, Atari, Macintosh, MIDI-Workstations, MIDI-File-Player mit DOS-kompatiblem Diskettenlaufwerk", "Kopie", "Kopie", "CD u.d.T.: Alda Merini presenta La cosa più bella che ci sia", "Kopie?", "Repr.: New York, NY [u.a.] : Johnson", "Übers. des Hauptsacht.: Gesetzlicher Umweltschutz in Hongkong", "Includes bibliographical references and index", "Übers. des Hauptsacht.: Das vollständige Verzeichnis chinesischer Unternehmen im Bereich der Produktionsmittelzirkulation", ". - Als Beil. zur Buchausg.", "Mikrofiche-Ausg.: 3 Mikrofiches : 24x. Best.-Nr. Diss ETH 12734", "Includes index", "Enthält Tondokumente von 1949 - 1974." and – my favorite – "Kopft"

**Comment by acka47** [comment]
As these (foot)notes seem to cover heterogenous topics, I suggest using a generic property for this: `skos:note`. Desired outcome (snippet):

```javascript
{
  "@graph" : [ {
    "@id" : "http://lobid.org/resource/HT018362113",
    "note": "Dokument ist gesperrt, neue Version unter urn:nbn:de:hbz:38m-0000009024"
  } ]
}
```

This means, we will hav to add this to the JSON-LD context: `"note": "http://www.w3.org/2004/02/skos/core#note"`

**Comment by acka47** [comment]
Note to self: Remember to notify at https://jira.hbz-nrw.de/browse/FRL-87 when changes are deployed.

**Comment by dr0i** [comment]
How should the label of this be? "Änderungshinweis" ("change note")?
I need the label for i.a. https://github.com/hbz/lobid-rdf-to-json/blob/master/src/main/resources/context.json.

**Comment by acka47** [comment]
Take "Hinweis".

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production.
