### ISSUE TITLE
Add exceptions to bibo:Book typing for AV-documents

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#757]
Reported by publisso stakeholders, see https://jira.hbz-nrw.de/browse/FRL-99 in our internal Jira.

There are several cases where audio-visual media are typed as `bibo:Book` as they have an `m` in field 051. See for instance audio-visual media in NWBib: http://lobid.org/nwbib/search?q=*&medium=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FAudioVisualDocument Most of them are typed as "Book".

We will have to add another exception to bibo:Book typing to the [current morph, lines 309-322](https://github.com/lobid/lodmill/blob/ac0602793aafebdd835091d7803b869a58ee663b/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L309-L322).

I will think about what exactly to do.

**Comment by acka47** [comment]
For the hole catalog, we are taling about 17k records, see http://alpha.lobid.org/resources/search?medium=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2Faudiovisualdocument&t=book

**Comment by ChristophEwertowski** [comment]
A clarification: Videos aren't books, see [query for videos](http://lobid.org/resources/search?medium=http%3A%2F%2Frdaregistry.info%2FtermList%2FRDACarrierType%2F1050&aggregations=medium.id). But of 38.748 AudioVisualDocuments [17.191 are also books](http://lobid.org/resources/search?medium=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FAudioVisualDocument&t=book&aggregations=medium.id). Renaming this issue to avoid confusion.
