### ISSUE TITLE
Two "title" for one resource

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#761]
Example http://lobid.org/resource/BT000003404 (snippet): 

```javascript
{
    "@id" : "http://lobid.org/resource/BT000003404",
    "title" : [ "Deutschland 1:300000", "Deutschland, 2: Nordrhein-Westfalen, Niedersachsen-Süd" ]
}
```

From the [source](http://lobid.org/resource?id=BT000003404&format=source):

```xml
<datafield tag="310" ind1="-" ind2="2">
  <subfield code="a">Deutschland &lt;1:300000></subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="1">
  <subfield code="a">Nordrhein-Westfalen, Niedersachsen-Süd</subfield>
</datafield>
<datafield tag="331" ind1="-" ind2="2">
  <subfield code="a">Deutschland</subfield>
</datafield>
```

Obviously, both the title of the resource and the superordinated resource are taken as a title. I think, these should rather be concatinated

**Comment by acka47** [comment]
One title is generated as usually by taking the 331 from the superordinated resource with concatenated volume information from 090 and adding the 331 from the volume, see [current morph, lines 502ff](https://github.com/lobid/lodmill/blob/b37d5fad2f0b2402b4d827e9bcfbf47066d891da/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L502-L518). Obviously, we don't have a rule for when there also is a 310 from the superordinated resource. I think, in this case we should ojust ignore the 310. Desired outcome for the example:

```javascript
{
    "@id" : "http://lobid.org/resource/BT000003404",
    "title" : [ "Deutschland, 2: Nordrhein-Westfalen, Niedersachsen-Süd" ]
}
```

**Comment by dr0i** [comment]
Fix deployed to staging.

**Comment by acka47** [comment]
From the comment above (removed the array for the `title` filed):

> Desired outcome for the example:

> ```javascript
{
    "@id" : "http://lobid.org/resource/BT000003404",
    "title" :  "Deutschland, 2: Nordrhein-Westfalen, Niedersachsen-Süd" 
}
```

Currently on staging (snippet): 

```javascript
{
  "@id" : "http://lobid.org/resource/BT000003404",
  "title" : "Deutschland 1:300000"
```

Obviously, not the `331`s plus `090` were taken for the title (as requested) but the other way round, the `310` from the superordinated resource was taken and the rest was ignored. Please adjust the morph accordingly so that the `310` from the superordinated resource is ignored.

**Comment by dr0i** [comment]
Ok, as this was just a sideeffect of dealing with #762 I will fix this when the latter is closed.

**Comment by dr0i** [comment]
Deployed to staging.

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production, closing.
