### ISSUE TITLE
Missing information from some subfields of creator/contributor

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#767]
> Uns fiel auf, dass beim Datentransfer von der 
> HBZ-Titeldatei in die Lobid-Datenbank bei mehrgliederigen Normdaten 
> Unterfelder abgeschnitten werden d.h. es gehen Daten verloren.
> 
> Das bewirkt einerseits eine verkürzte Anzeige der Normdaten in den 
> NWBib-Titelaufnahmen, andererseits hat dies Auswirkungen auf die 
> Rechercheergebnisse.
> 
> Zunächst einige Beispiele für die *abgeschnittene Anzeige* von Normdaten 
> in der Einzeltrefferanzeige:
> ...
> http://lobid.org/nwbib/BT000168595  Mitwirkung [HBZ01-Feld 200 *b*]: 
> Westfalen-Lippe. Fraktion Bündnis 90, Die Grünen à es fehlt die Anzeige 
> des 1. Unterfeld *b* „Landschaftsversammlung“  d.h. hier fehlt das 
> mittlere Feld
> 
> http://lobid.org/nwbib/HT016604323  Autor/in [HBZ01-Feld 200]: „null“ à 
> es fehlt die komplette Anzeige des Namens „PsychiatrieVerbund Westfalen 
> | Beschwerdekommission“
> 
> http://lobid.org/nwbib/BT000082463 Mitwirkung [HBZ01-Feld 200 *b*]: 
> Sozialdemokratische Partei Deutschland. Ortsverein à es fehlt die 
> Anzeige des Unterfeld *h* Warendorf
> 
> http://lobid.org/nwbib/HT016302156 Autor/in [HBZ01-Feld 200]: „null“ à 
> es fehlt die komplette Anzeige des Namens „Sozialdemokratische Partei 
> Deutschlands | b Ortsverein | *h* Warendorf

**Comment by acka47** [comment]
Made a separate issue (#768) for 

> http://lobid.org/nwbib/HT016604323  Autor/in [HBZ01-Feld 200]: „null“ à 
> es fehlt die komplette Anzeige des Namens „PsychiatrieVerbund Westfalen 
> | Beschwerdekommission“

**Comment by acka47** [comment]
The last error with http://lobid.org/resource/HT016302156/about is also covered by #768.

**Comment by acka47** [comment]
Regarding 
> http://lobid.org/nwbib/BT000082463 Mitwirkung [HBZ01-Feld 200 *b*]: 
> Sozialdemokratische Partei Deutschland. Ortsverein à es fehlt die 
> Anzeige des Unterfeld *h* Warendorf

the problem is that the content of subfield `h` is wrapped in angle brackets (`<>`) which is the reason that it is not seen in the browser. There are two possible solutions:

1. Adjust [line 828 in the current morph](https://github.com/lobid/lodmill/blob/9710b449d88e981dc8080e2a9327a1c4dc5f1966/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml#L828) to use normal brackets (`()`) instead of angele brackets.
2. Adjust the NWBib frontend to show contents in angle brackets.

I tend to number 1. and will think about it some more.

**Comment by acka47** [comment]
That leaves us with 

> http://lobid.org/nwbib/BT000168595  Mitwirkung [HBZ01-Feld 200 *b*]: 
> Westfalen-Lippe. Fraktion Bündnis 90, Die Grünen à es fehlt die Anzeige 
> des 1. Unterfeld *b* „Landschaftsversammlung“  d.h. hier fehlt das 
> mittlere Feld


[Source](http://lobid.org/resource?id=BT000168595&format=source) (snippet):

```xml
<datafield tag="200" ind1="b" ind2="1">
  <subfield code="k">Westfalen-Lippe</subfield>
  <subfield code="b">Landschaftsversammlung</subfield>
  <subfield code="b">Fraktion Bündnis 90, Die Grünen</subfield>
  <subfield code="9">(DE-588)5265186-1</subfield>
</datafield>
```

Current JSON (snippet):

```javascript
{
    "@id" : "http://d-nb.info/gnd/5265186-1",
    "preferredName" : "Westfalen-Lippe. Fraktion Bündnis 90, Die Grünen",
    "preferredNameForTheCorporateBody" : "Westfalen-Lippe. Fraktion Bündnis 90, Die Grünen"
```

These looks very similar to #770 the only difference being that the problem there is with corporate bodies as subject, not creator. @dr0i Is this case covered with #770 or should I open a separate issue for this?

**Comment by dr0i** [comment]
As this concerns an other field it must be worked on separately, even if the underlying problem is indeed the same.

**Comment by acka47** [comment]
> As this concerns an other field it must be worked on separately, even if the underlying problem is indeed the same.

Did so, see #772.

**Comment by acka47** [comment]
Re. https://github.com/lobid/lodmill/issues/767#issuecomment-165785790, I opened #773. 

Closing this issue as everything is covered in more specific issues.
