### ISSUE TITLE
Two preferredNames for one corporate body

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#768]
Reported by NWBib stakeholder I.N. on 2015-12-02. Example http://lobid.org/resource/HT016604323/about.

[JSON](http://lobid.org/resource?id=HT016604323&format=source) (snippet):
```javascript
{
  "@graph" : [ {
    "@id" : "http://d-nb.info/gnd/16090142-X",
    "preferredName" : [ "PsychiatrieVerbund Westfalen. Beschwerdekommission", "PsychiatrieVerbund Westfalen" ],
    "preferredNameForTheCorporateBody" : [ "PsychiatrieVerbund Westfalen. Beschwerdekommission", "PsychiatrieVerbund Westfalen" ]
  } ]
}
```

There should only be _one_ preferredName not an array of two or more. (There are obvious similarities to #761. I don't know whether the cause of the two problems is similar, though.)

**Comment by dr0i** [comment]
I changed it to be just one entry. I also would suggest to use a commata as delimiter, like `"PsychiatrieVerbund Westfalen, Beschwerdekommission"`. It strikes me odd if I am seeing sth like `"Niedersaches. Süd"`. What do you think?

**Comment by dr0i** [comment]
Deployed to minimal staging, see http://gaia.hbz-nrw.de:9200/resources/resource/HT016604323.

**Comment by acka47** [comment]
+1 

> I also would suggest to use a commata as delimiter, like `"PsychiatrieVerbund Westfalen, Beschwerdekommission"`. It strikes me odd if I am seeing sth like `"Niedersachen. Süd"`. What do you think?

lLet's keep the periods for now as customers haven't requested this change yet.

**Comment by dr0i** [comment]
Deployed with fulldump, closing.

**Comment by dr0i** [comment]
Data exists in index 2.0 at gaia. Now you can lookup that index to use the labels in the frontend.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/HT016604323

**Comment by acka47** [comment]
> Deployed to staging: http://test.lobid.org/nwbib/HT016604323

+1

**Comment by acka47** [comment]
(We are doing ticket recycling using transformation tickets for deployment in NWBib, don't we? I don't mind and as long as the environment benefits...)

**Comment by fsteeg** [comment]
> Reported by NWBib stakeholder [...]

I'd argue this was actually an NWBib issue in the first place :-)
