### ISSUE TITLE
Missing subfield `x` for geographica

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#769]
From https://github.com/lobid/lodmill/issues/766#issuecomment-165767182

Examples:

[HT017309948](http://lobid.org/resource?id=HT017309948&format=source) (snippet):
```xml
<datafield tag="902" ind1="-" ind2="1">
  <subfield code="g">Haus Merfeld</subfield>
  <subfield code="h">Merfeld</subfield>
  <subfield code="x">Sankt Antonius Abt</subfield>
  <subfield code="9">(DE-588)7856043-3</subfield>
</datafield>
```
Current JSON (snippet):

```javascript
{
    "@id" : "http://d-nb.info/gnd/7856043-3",
    "preferredName" : "Haus Merfeld, Merfeld",
    "preferredNameForThePlaceOrGeographicName" : "Haus Merfeld"
  }
```

Subfield x might also be repeated, see e.g. [HT013925945](http://lobid.org/resource?id=HT013925945&format=source) (snippet):
```xml
<datafield tag="902" ind1="-" ind2="1">
<subfield code="g">Bökenförde</subfield>
<subfield code="x">Schloss Schwarzenraben</subfield>
<subfield code="x">Sankt Antonius Abt</subfield>
<subfield code="9">(DE-588)7764102-4</subfield>
</datafield>
```

Current JSON:

```javascript
{
    "@id" : "http://d-nb.info/gnd/7764102-4",
    "preferredName" : "Bökenförde",
    "preferredNameForThePlaceOrGeographicName" : "Bökenförde"
  }
```

**Comment by dr0i** [comment]
Deployed to small test staging to index 2.0, see e.g. http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT013925945

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
Deployed to full index, closing.

**Comment by dr0i** [comment]
Data exists in index 2.0 at gaia. Now you can lookup that index to use the labels in the frontend.

**Comment by fsteeg** [comment]
Deployed to staging:

http://test.lobid.org/nwbib/HT017309948
http://test.lobid.org/nwbib/HT013925945

**Comment by acka47** [comment]
+1
