### ISSUE TITLE
Missing subfield `b` for corporate bodies

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#770]
From https://github.com/lobid/lodmill/issues/766#issuecomment-165767182.

Example [HT017150239](http://lobid.org/resource?id=HT017150239&format=source) (snippet): 

```xml
<datafield tag="902" ind1="-" ind2="1">
<subfield code="k">Westfalen-Lippe</subfield>
<subfield code="b">Amt für Denkmalpflege in Westfalen</subfield>
<subfield code="b">Fachbereich Praktische Denkmalpflege und Baukultur</subfield>
<subfield code="9">(DE-588)7856688-5</subfield>
</datafield>
```

Current JSON:

```javascript
{
    "@id" : "http://d-nb.info/gnd/7856688-5",
    "preferredName" : "Westfalen-Lippe",
    "preferredNameForTheCorporateBody" : "Westfalen-Lippe"
  }
```

**Comment by dr0i** [comment]
The problem is the iteration of subfield b. Seems to be valid in MARC21 (see http://www.loc.gov/marc/bibliographic/bd110.html ) and so should be for MAB2, too.

**Comment by dr0i** [comment]
Deployed to small test set into inde 2.0, see e.g. http://gaia.hbz-nrw.de:9200/resources-staging/resource/HT017150239 .

**Comment by acka47** [comment]
I see this is already merged. Nonetheless, here is a +1 from me.

**Comment by dr0i** [comment]
Sigh , yes, I first merged branches in wrong order resulting in a mess. Will comment the order next time in issues so that this will hopefully not occur again.

**Comment by dr0i** [comment]
Deployed to full index, closing.

**Comment by dr0i** [comment]
Data exists in index 2.0 at gaia. Now you can lookup that index to use the labels in the frontend.

**Comment by fsteeg** [comment]
Already deployed as part of general switch to new data for presentation, see:

http://nwbib.de/HT017150239

**Comment by acka47** [comment]
+1. Closing.
