### ISSUE TITLE
Content from field 200 subfield b missing in RDF

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#772]
Reported by NWBib stakeholder I.N. on 2015-12-02:

> http://lobid.org/nwbib/BT000168595  Mitwirkung [HBZ01-Feld 200 *b*]: 
> Westfalen-Lippe. Fraktion Bündnis 90, Die Grünen à es fehlt die Anzeige 
> des 1. Unterfeld *b* „Landschaftsversammlung“  d.h. hier fehlt das 
> mittlere Feld

From https://github.com/lobid/lodmill/issues/767#issuecomment-165789343:

[Source](http://lobid.org/resource?id=BT000168595&format=source) (snippet):

```xml
<datafield tag="200" ind1="b" ind2="1">
  <subfield code="k">Westfalen-Lippe</subfield>
  <subfield code="b">Landschaftsversammlung</subfield>
  <subfield code="b">Fraktion Bündnis 90, Die Grünen</subfield>
  <subfield code="9">(DE-588)5265186-1</subfield>
</datafield>
```

Current JSON (snippet):

```javascript
{
    "@id" : "http://d-nb.info/gnd/5265186-1",
    "preferredName" : "Westfalen-Lippe. Fraktion Bündnis 90, Die Grünen",
    "preferredNameForTheCorporateBody" : "Westfalen-Lippe. Fraktion Bündnis 90, Die Grünen"
```

**Comment by dr0i** [comment]
Fixed and deployed to index 2.0, see http://gaia.hbz-nrw.de:9200/resources/resource/BT000168595 .

**Comment by acka47** [comment]
+1

**Comment by dr0i** [comment]
@fsteeg Data exists in index 2.0 at gaia. Now you can lookup that index to use the labels in the frontend.

**Comment by fsteeg** [comment]
Deployed to staging: http://test.lobid.org/nwbib/BT000168595

**Comment by acka47** [comment]
> Deployed to staging: http://test.lobid.org/nwbib/BT000168595

+1
