### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by jbaiter** [lobid/lodmill#786]
This has already been a solved issue in the past (https://github.com/lobid/lodmill/issues/423), but it seems that the `Acces-Control-Allow-Origin` header  has been removed since.
Would it be possible to re-enable it? I would like to use the API for  some auto-completion forms in a web application I'm developing and I'd hate to proxy it through my server just to get around the CORS restrictions.

**Comment by acka47** [comment]
Here's the original (now closed) issue: https://github.com/lobid/lodmill/issues/423

**Comment by acka47** [comment]
@jbaiter Could you please specify about which endpoint you are talking? As far as I can see, it works for the endpoints in production: https://lobid.org/resource and http://lobid.org/subject and http://lobid.org/organisation.

It also seems to work for http://beta.lobid.org/organisations. The only one where it doesn't work is the lobid-resources API 2.0 (in beta) with the hbz union catalogue data, e.g. http://lobid.org/resources/HT014681992. Are you already using this endpoint?

**Comment by jbaiter** [comment]
I'm using the `/subject` endpoint, here are the headers that I get from my shell with `httpie`:

```
GET /subject?q=Proserpina&format=full&type=http://d-nb.info/standards/elementset/gnd%23Person HTTP/1.1
Connection: keep-alive
Host: lobid.org
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: HTTPie/0.9.2



HTTP/1.1 200 OK
Date: Tue, 01 Mar 2016 09:29:52 GMT
Content-Type: application/json; charset=utf-8
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 3416
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
```

I also don't see the header on any of the endpoints you linked to :-/

**Comment by fsteeg** [comment]
#423 is about CORS support for the context document, which is required for JSON-LD with linked contexts in the playground. Our current production endpoints never had CORS support, but they support JSONP callbacks.

For your query: http://lobid.org/subject?q=Proserpina&format=full&type=http://d-nb.info/standards/elementset/gnd%23Person&callback=jsonp

See also `/subject` sample usage at: http://lobid.org/api#auto-suggest-examples

**Comment by jbaiter** [comment]
Ouch, sorry, I complete skipped over that part! Thanks for the clarification :-)

**Comment by acka47** [comment]
i guess we can close this then. Closing.
