### ISSUE TITLE
Offer API that maps LOD properties to human readable labels

### ISSUE THREAD

**Issue by fsteeg** [lobid/lodmill#79]
e.g. `http://iflastandards.info/ns/isbd/elements/P1004` -> `Title`

We should use this API internally for the localisation of the main page and the RDFa/HTML representations of results. At the same time, this API can be used externally to display API results without knowing the exact properties used (e.g. 'display each property in a table, using the label the API delivers'), and therefore decrease coupling between presentation and data.

**Comment by acka47** [comment]
We use etikett for this now. Closing.
