### ISSUE TITLE
URIs in morph don't resolve anymore

### ISSUE THREAD

**Issue by ChristophEwertowski** [lobid/lodmill#795]
Two URIs in [morph-hbz01-to-lobid.xml](https://github.com/lobid/lodmill/blob/master/lodmill-rd/src/main/resources/morph-hbz01-to-lobid.xml) don't resolve anymore.
1. http://purl.org/ontology/daia/label which is referenced in line 778. The ontology moved to [GitHub] but I don't know if we really should link to the daia.schema.json file.
2. http://rdvocab.info/termList/prodManuscript/1002 in line 325.

**Comment by acka47** [comment]
@nichtich Is it intended that DAIA property and class URIs don't resolve anymore?

`curl -i -L -H "Accept: application/rdf+xml" http://purl.org/ontology/daia/` even gives a 404:

```
HTTP/1.1 404 NOT FOUND
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 17 Jan 2017 10:43:53 GMT
Content-Type: text/html
Content-Length: 233
Connection: keep-alive
```

`curl -i -L -H "Accept: application/rdf+xml" http://purl.org/ontology/daia` gives a redirect to an empty .owl file on GitHub:

```
HTTP/1.1 302 FOUND
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 17 Jan 2017 10:44:06 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 194
Connection: keep-alive
Location: http://uri.gbv.de/ontology/daia
Access-Control-Allow-Origin: *

HTTP/1.1 303 See Other
Date: Tue, 17 Jan 2017 10:44:06 GMT
Server: Apache/2.2.22 (Ubuntu)
X-Powered-By: PHP/5.3.10-1ubuntu3.25
Location: http://gbv.github.io/daiaspec/daia.owl
Vary: Accept-Encoding
Content-Length: 0
Content-Type: text/html

HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: application/octet-stream
Last-Modified: Mon, 28 Sep 2015 09:05:33 GMT
Access-Control-Allow-Origin: *
Expires: Tue, 17 Jan 2017 10:47:53 GMT
Cache-Control: max-age=600
X-GitHub-Request-Id: C71B4C21:2DB6D:B2A9DD4:587DF401
Content-Length: 116
Accept-Ranges: bytes
Date: Tue, 17 Jan 2017 10:44:06 GMT
Via: 1.1 varnish
Age: 373
Connection: keep-alive
X-Served-By: cache-hhn1532-HHN
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1484649846.988947,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: 4a831d9301c950559d25c71e6e3549d4cfd15c0d

<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
</rdf:RDF>

```

**Comment by ChristophEwertowski** [comment]
As an alternative (indeed it's the only alternative) we could take http://purl.org/ontology/bibo/Manuscript for the second URI. Even Schema.org doesn't seem to have this [publication type](http://schema.org/CreativeWork) (maybe internet firms don't deal with it).
If I adjust the redirected URI to http://www.rdaregistry.info/termList/prodManuscript/1002 I get the message that "GitHub Pages is temporarily down for maintenance." So maybe that would be the right URI.

**Comment by acka47** [comment]
There also is [bf:Manuscript](http://id.loc.gov/ontologies/bibframe/Manuscript). They have two different underlying meanings of the term "Manuscript", though:

- bibo: "An unpublished Document, which may also be submitted to a publisher for publication."
- bibframe: "Resource that is written in handwriting or typescript. These are generally unique resources."

There are currently 530 resources with this medium type in lobid, see http://alpha.lobid.org/resources/search?q=*&medium=http%3A%2F%2Frdvocab.info%2FtermList%2FprodManuscript%2F1002. Obviously, "Manuskript" is used in both meanings of the term in the union catalogue. If you [look at the oldest resources](http://alpha.lobid.org/resources/search?q=*&medium=http%3A%2F%2Frdvocab.info%2FtermList%2FprodManuscript%2F1002&size=100&sort=oldest), these are obviously manuscripts in the bibframe sense. If you look at [the latest resources](http://alpha.lobid.org/resources/search?q=*&medium=http%3A%2F%2Frdvocab.info%2FtermList%2FprodManuscript%2F1002&size=100) these are definitely manuscripts in the bibo sense. However, as we are only talking about 530 resources, we shouldn't put much more effort into it as we already did.

I also tend to using `bibo:Manuscript` as it sounds a bit to be the more general class. (I think for some reason we aimed at using `skos:Concept`s on the `dct:medium` property but we already have some exceptions. Thus, we can as well use `bibo:Manuscript` (which is an `owl:Class`).)

**Comment by ChristophEwertowski** [comment]
Another reason is the depiction of the publication year on the right side. Most of the publications are from ca. 1775 and later. Since typewriters were used in mass not until much later one can suppose that most of the works are (unpublished) prints.

**Comment by ChristophEwertowski** [comment]
Looked in the [documentation](https://gbv.github.io/daia-rdf/daia.html) of the DAIA ontology (2015-04-22) for the namespace. In point 2.1 it's written there that http://purl.org/ontology/daia# may be the new namespace and in fact it is. It forwards one to the [documentation of the API](http://gbv.github.io/daia/daia.html) of 2016-02-26. Update: Unter point 2.3 it is written that the namespace **is** the URI they wrote down in 2.1. You still can't get rdf.

**Comment by ChristophEwertowski** [comment]
@nichtich I tried to get an RDF file of the DAIA ontology but got none by curl-ing: ```curl -i -L -H "Accept: application/rdf+xml" http://purl.org/ontology/daia```. Am I looking at the wrong place or is the RDF offline?

**Comment by ChristophEwertowski** [comment]
http://id.loc.gov/ontologies/bibframe/ShelfMark.rdf ([HTML](http://id.loc.gov/ontologies/bibframe.html#p_shelfMark))would be a good replacement for daia/label. What do you mean @acka47 ?

**Comment by acka47** [comment]
The problem with bf:shelfMark is that it is an owl:ObjectProperty. Speaking to @ChristophEwertowski offline, we decided to add a property to lobid vocab, see https://github.com/hbz/lobid-vocabs/pull/59.

**Comment by acka47** [comment]
After merging https://github.com/hbz/lobid-vocabs/pull/59 we have to replace `daia:label` by `lv:callNumber` and `http://rdaregistry.info/termList/prodManuscript/1002` by `bibo:Manuscript`.

**Comment by dr0i** [comment]
Deployed to stage. @fsteeg ready for UI update. The only change is that `Medium` changed to `bibo/Manuscript`, see e.g. http://stage.lobid.org/resources/TT001726537?format=json.

**Comment by fsteeg** [comment]
Deployed to staging, see medium facet: http://stage.lobid.org/resources/search

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
+1
