### ISSUE TITLE
Minimize index updates to incremental ones

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#798]
As discussed with @fsteeg:
as we don't change the data of API 1.0 anymore it's sufficient to index only incremental updates. The weekly complete basedump indexing will be omitted. Thus, we will not have reflected deletions of resources - but that doesn't strikes us as important for this deprecated API. Hint: switch to [API 2.0](https://github.com/hbz/lobid-resources).

**Comment by dr0i** [comment]
Done by adapting crontab. Commited to internal repo. Closing.

**Comment by fsteeg** [comment]
I thought we had discussed this topic for the hbz01/mabxml index. Fine with me for API 1.x too though.

**Comment by dr0i** [comment]
Reverted that because of #799.
