### ISSUE TITLE
Missing resource in Lobid v1

### ISSUE THREAD

**Issue by jschnasse** [lobid/lodmill#799]
HT019372056
http://lobid.org/resource/HT019372056/about

**Comment by dr0i** [comment]
Triggered indexing of fulldump. Will be ready tomorrow.
Also reverted #798 so that the "self-healing" process in the case of update errors can take effect.

**Comment by acka47** [comment]
The resource is there now, see http://lobid.org/resource/HT019372056/about. Closing.

**Comment by dr0i** [comment]
The new index is build, but it is aliased to staging.
Coincidence: just yesterday the resource was modified so it was updated with the daily update process.
I am switching the alias now.
