### ISSUE TITLE
Shut down old lobid-organisation

### ISSUE THREAD

**Issue by dr0i** [lobid/lodmill#800]
The old lobid.org/organisation is deprecated and should be shut down one day in favor of the new lobid.org/organisations. A permament redirect would be best. But as the data structure and API is incompatible, this will break things.

So, who will be affected ? Judge  by looking at the numbers (apache logs of this month).
Old organisations ( 167.245 requests in total):
`emphytos:~ # grep "GET /organisation/" /var/log/apache2/access_log  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
`
```
  132956 193.30.112.170
  23600 134.147.247.53
   1251 68.180.229.93
    784 68.180.228.157
    390 5.9.106.230
```

 Compare with new organisations (131.174 requests in total):
`emphytos:~ # grep "GET /organisations/" /var/log/apache2/access_log  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5`
```
  86193 193.30.112.170
   1409 10.1.1.222
    767 69.30.198.178
    715 213.133.111.165
    711 88.198.16.12
```
=====> 
- It looks like old organisation is mainly used by ourselves (old lobid.org) and Bochum. Leaving ~10.000 lookups. A good part of them are bots.

- It looks like new organisations is more often used by others - around ~40.000 lookups. A good part of them are also bots.

**Comment by acka47** [comment]
I suggest to fix https://github.com/hbz/lobid-organisations/issues/373, https://github.com/hbz/lobid-organisations/issues/41 and – at least a good part of – https://github.com/hbz/lobid-organisations/issues/128 and then announce the shut down of 1.0 for the beginning of November on the list and on twitter.

**Comment by acka47** [comment]
We should now schedule a shut down.

**Comment by acka47** [comment]
Here are the newest numbers:

`emphytos:~ # grep "GET /organisation/" /var/log/apache2/access_log  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
`
```
  74512 193.30.112.170
   3076 10.7.1.37
   2982 10.9.0.11
   1622 134.147.247.53
    669 68.180.228.153
```

`emphytos:~ # grep "GET /organisations/" /var/log/apache2/access_log  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5`
```
  36271 193.30.112.170
   1754 88.99.19.242
   1581 10.7.4.13
   1218 10.9.0.11
    947 193.30.112.99
```

@dr0i said above:

> It looks like old organisation is mainly used by ourselves (old lobid.org) and Bochum

I don't think that we actually use the old lobid-organisations ourselves. lobid-resources 1.x doesn't use it and NWBib also was switched to the 2.0 service in 2015 (https://github.com/hbz/nwbib/issues/121). So, this rpobably comes from other places in the hbz, e.g. AFAIK https://www.hbz-nrw.de/produkte/verbunddienstleistungen/verbundbibliotheken uses lobid-organisations. I will contact @peterreimer.

**Comment by acka47** [comment]
> I will contact @peterreimer.

Just talked to him on the telephone. He just recently switched to lobid-organisations. There are other requests from hbz getting the short names by ISIL like `GET /organisation/DE-Kn38?format=short.altLabel`. @dr0i confirmed that this comes from NWbib. Opened https://github.com/hbz/nwbib/issues/401.

**Comment by acka47** [comment]
The switch to lobid-organisations 2.0 will take some time for NWBib, see https://github.com/hbz/nwbib/issues/401#issuecomment-337520487. Will revisit this when NWBib has switched.

**Comment by acka47** [comment]
Here are the newest numbers:

`emphytos:~ # grep "GET /organisation/" /var/log/apache2/access_log  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
`
```
   1807 34.229.67.226
   1377 52.87.215.202
    637 216.244.66.245
    443 88.198.66.230
    332 34.201.165.59
```

`emphytos:~ # grep "GET /organisations/" /var/log/apache2/access_log  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5`
```
  22657 193.30.112.170
   3141 10.9.0.11
   2554 10.1.1.61
   1513 144.76.185.181
   1419 5.9.63.162
```

**Comment by acka47** [comment]
I think we can shut the old service down in may without hurting anybody. Of course, we will have to inform API via Twitter and mailing list set up 301 redirects to the new service before switching it off.

**Comment by acka47** [comment]
Shutdown is scheduled for 2018-10-31, see http://blog.lobid.org/2018/07/19/lobid-1-shutdown.html

**Comment by dr0i** [comment]
As https://github.com/lobid/lodmill/issues/802 and https://github.com/hbz/lobid-resources/issues/947 are resolved this effectively is also a shutdown for lobid-organisation 1.0.
So - closing.
