### ISSUE TITLE
Shut down old GND service

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#801]
As we have problems with updates we don't want to solve, we should think about shutting down the service in the near future. @jschnasse made clear that he could easily switch to http://test.lobid.org/authorities. (We would have to add support for auto-suggest and test vs. beta server befor such achange.)

However, to see if we can actually switch off the service quite soon we have to know who is currently using it. @dr0i could you please provide some insight as you already did for lobid-organisations 1.0 (see #800)?

**Comment by jschnasse** [comment]
Currently I use the /subject endpoint with q parameter AND
-  with ?t=http://d-nb.info/standards/elementset/gnd#SubjectHeadingSensoStricto for subjects
-  with ?t=http://d-nb.info/standards/elementset/gnd#Person for persons
-  with ?t=http://d-nb.info/standards/elementset/gnd#CorporateBody for corporateBodies

[I use the response](https://github.com/hbz/zettel/blob/master/app/controllers/ZettelController.java#L376) to generate input for my UI-Widgets.

**Comment by dr0i** [comment]
Grepping for `subject`:

> emphytos:/var/log/apache2 # grep "GET /subject" /files/weywot4/logs_apache_emphytos/access_log-20170901  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
    669 193.30.112.174
     44 141.57.19.7
     24 82.80.244.59
     18 68.180.228.153
     13 45.55.235.114

<= 669 hits from ellinet

Grepping for `person`:

>    emphytos:/var/log/apache2 # grep "GET /person" /files/weywot4/logs_apache_emphytos/access_log-20170901  | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
   4120 131.130.92.253
    102 91.229.60.66
     38 68.180.228.153
     21 82.80.244.59
     19 68.180.228.24

<= 4120 hits from https://exhibitions05-15.kugb.univie.ac.at/

**Comment by acka47** [comment]
Ok, this is not much and doesn't justify putting resource in fixing the updates. I will contact people at http://exhibitions.univie.ac.at as soon as we have a beta service with updates running at https://lobid.org/authorities.

**Comment by acka47** [comment]
I just repeated the log queries for beginning of October.

For subject:

 ```
emphytos:/var/log/apache2 # grep "GET /subject" /files/weywot4/logs_apache_emphytos/access_log-20171001 | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
 298224 194.94.133.3
   1627 134.93.90.250
    661 193.30.112.174
     61 134.93.105.125
     15 193.30.112.175
```
For person:

```
emphytos:/home/pohl # grep "GET /person" /files/weywot4/logs_apache_emphytos/access_log-20171001 | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
   1608 131.130.92.253
    110 91.229.60.66
     58 134.93.105.125
     27 68.180.228.153
     23 134.93.90.250
```

We obviously have won new (test) users.

```
$ whois 194.94.133.3
...
inetnum:        194.94.132.0 - 194.94.135.255
netname:        SPKNET
descr:          Stiftung Preussischer Kulturbesitz
descr:          Staatsbibliothek zu Berlin
country:        DE
...
```

```
...
$ whois 134.93.90.250
...
inetnum:        134.93.0.0 - 134.93.255.255
netname:        UNI-MAINZ-B
descr:          Johannes Gutenberg-Universitaet, Mainz
descr:          Zentrum fuer Datenverarbeitung
descr:          55099 Mainz
country:        DE
...
```

Maybe we should point people more clearly to lobid.org/gnd ...

**Comment by acka47** [comment]
Here are the current log queries:

For subject:
```
# grep "GET /subject" /files/weywot1/logs_apache_emphytos/access_log-20180401 | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
     33 35.153.33.36
     24 52.3.220.73
     16 54.209.230.242
     16 54.208.83.226
     16 52.204.90.113
```

For person:
```
# grep "GET /person" /files/weywot1/logs_apache_emphytos/access_log-20180401 | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n5
   1054 131.130.92.253
    156 134.100.253.253
     34 35.153.33.36
     25 52.3.220.73
     22 217.182.192.89
```

The ~1000 are coming from a test server for an Austrian project that obviously does not use lobid in production, see https://private-kuenstlernachlaesse-brandenburg.de which has as ip `$ dig +short private-kuenstlernachlaesse-brandenburg.de
195.37.232.142`.

Thus, we can safely shut down the service in May and will have to announce the shutdown shortly.

**Comment by acka47** [comment]
Shutdown is scheduled for 2018-10-31, see http://blog.lobid.org/2018/07/19/lobid-1-shutdown.html

**Comment by dr0i** [comment]
All redirects are done, old ES-cluster is stopped, so is play app for Api 1.0, see https://github.com/lobid/lodmill/issues/800.
See also https://github.com/lobid/lodmill/issues/802 for lobid-organisations 1.0.
=> closing this one
