### ISSUE TITLE
Shut down old lobid-resources

### ISSUE THREAD

**Issue by acka47** [lobid/lodmill#802]
The main user of the old service is @jschnasse. Here are some current statistics from emphytos:

```
# grep "GET /resource" /files/weywot1/logs_apache_emphytos/access_log-20180401 | awk '{print $1}' | sort -n | uniq -c | sort -nr | head -n10
1971822 193.30.112.170
 360178 193.30.112.176
 322817 193.30.112.174
 162238 10.9.0.11
 149207 10.9.0.10
  52960 40.65.117.118
  37091 10.6.4.81
  10110 10.1.1.4
   7221 10.1.1.111
   5926 10.1.1.174
```

As this almost exclusively traffic from inside the hbz, we can shut down access from outside hbz in May as discussed offline.

**Comment by jschnasse** [comment]
I'm on a good way towards lobid v2. My plan is to remove the last dependency in **June 2018**. I'll let you know.

**Comment by acka47** [comment]
Shutdown is scheduled for 2018-10-31, see http://blog.lobid.org/2018/07/19/lobid-1-shutdown.html

**Comment by acka47** [comment]
To do:

- [x] Send reminder tweet and write email to lobid-list tomorrow
- [x] Redirect (HTTP 301) single resources (`/resource/{id}`, `/organisation/{id}`, `/subject/{id}`, `/person/{id}` to lobid 2.0)
[edit @dr0i]:~note  as `subject` and `person` had no direct ID access I did this for the  parameter `id=$ID`.~
- [x] As (HTTP 301)) above but for descriptions: `.../about`
- [x] Redirect `api.lobid.org` and `lobid.org/api` to ~:question:~ https://lobid.org 
[edit @dr0i]: `lobid.org/api` is the api_1.0's page, you intended that?
Anything else, @dr0i , @fsteeg ?

**Comment by acka47** [comment]
We also have to:

 - [x] Redirect search URLs. But where should they be reidrected?

One option for redirecting the searches is to *redirect them to the search endpoint of the respective new service*:
- `/resource?{anything}` --> `resources/search`
- `/item?{anything}` --> `resources/search`
-  `/organisation?{anything}` --> `organisations/search`
- `/subject?{anything}` --> `/gnd/search`
- `/person?{anything}` --> `/gnd/search`

Another option is to redirect them to the respective API documentation, e.g.:
- `/resource?{anything}` --> `resources/api`

Regarding the HTTP Status code I could not find a fitting code when redirecting multiple pages to one target page. My feeling is that 301 is probably the right code as well. 

It probably would also make sense to somehow give developers some information during the redirect that the old API has shut down. But I don't know what is the best way to do this.

**Comment by dr0i** [comment]
Did the rewriting. Note my two edits in the comment above.
Re: redirect search URLs: went with the second's proposal

>    /resource?{anything} --> resources/api

Summary:
1. ID lookups are redirected to their API 2.0 pendants
2. searches redirected to the API 2.0 documentation

**Comment by fsteeg** [comment]
Some samples:

- [x] http://lobid.org/resource?id=HT002189125
- [x] http://lobid.org/resource/HT002189125
- [x] http://lobid.org/resource?q=Suhrkamp
- [x] http://lobid.org/item?id=HT002189125:DE-468:EJRB1066
- [x] http://lobid.org/item/HT002189125:DE-468:EJRB1066
- [x] http://lobid.org/item?q=%22DE-5-4%22 (-> http://lobid.org/resources/api)
- [x] http://lobid.org/organisation?id=DE-605
- [x] http://lobid.org/organisation/DE-605
- [x] http://lobid.org/organisation?q=Einrichtung+ohne+Bestand
- [x] http://lobid.org/person?id=118580604
- [x] http://lobid.org/person/118580604
- [x] http://lobid.org/person?q=%22Bruder+von%22
- [x] http://lobid.org/subject?id=1706733-9
- [x] http://lobid.org/subject?q=de
- [x] http://lobid.org/search?id=HT002189125 (-> http://lobid.org)
- [x] http://lobid.org/search?q=Wittenberg (-> http://lobid.org)
- [x] http://lobid.org/api (-> http://lobid.org)

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
This adds to the apache-conf, for 80 and 443:

         # API 1.0 redirects
        RewriteRule ^/resource/(.*)/about /resources/$1 [R=301,NE,L]
        RewriteRule ^/resource/(.*) /resources/$1#! [R=301,NE,L]
        RewriteCond  %{QUERY_STRING}  ^id=(.*)$
        RewriteRule ^/resource$ /resources/%1#! [QSD,R=301,L,NE]
        RewriteCond  %{QUERY_STRING}  ^.*$
        RewriteRule ^/resource$ /resources/api [QSD,R=301,L]

        RewriteRule ^/item/(.*)/about /items/$1 [R=301,NE,L]
        RewriteRule ^/item/(.*) /items/$1#! [R=301,NE,L]
        RewriteCond  %{QUERY_STRING}  ^id=(.*)$
        RewriteRule ^/item$ /items/%1#! [QSD,R=301,L,NE]
        RewriteCond  %{QUERY_STRING}  ^q=(.*)$
        RewriteRule ^/item$ /resources/api [QSD,R=301,L,NE]
        RewriteCond  %{QUERY_STRING}  ^.*$
        RewriteRule ^/item$ /items/api [QSD,R=301,L]

        RewriteRule ^/organisation/(.*)/about /organisations/$1 [R=301,NE,L]
        RewriteRule ^/organisation/(.*) /organisations/$1#! [R=301,NE,L]
        RewriteCond  %{QUERY_STRING}  ^id=(.*)$
        RewriteRule ^/organisation$ /organisations/%1#! [QSD,R=301,L,NE]
        RewriteCond  %{QUERY_STRING}  ^.*$
        RewriteRule ^/organisation$ /organisations/api [QSD,R=301,L]

        RewriteRule ^/(subject|person)/(.*)/about /gnd/$2 [R=301,NE,L]
        RewriteRule ^/(subject|person)/(.*) /gnd/$2#! [R=301,NE,L]
        RewriteCond  %{QUERY_STRING}  ^id=(.*)$
        RewriteRule ^/(subject|person)$ /gnd/%1#! [QSD,R=301,L,NE]
        RewriteCond  %{QUERY_STRING}  ^.*$
        RewriteRule ^/(subject|person)$ /gnd/api [QSD,R=301,L]

        RewriteCond  %{QUERY_STRING}  ^.*$
        RewriteRule ^/search.* / [QSD,R=301,L]

        RewriteRule ^/api / [R=301,L]

**Comment by dr0i** [comment]
Note: ES-cluster at quaoar2/3 is stopped.
Resolving https://github.com/hbz/lobid-resources/issues/947 the play instance is now also stopped.

**Comment by acka47** [comment]
Great to see that you shut down the old services. Can this issue now be closed or is something still missing?

**Comment by dr0i** [comment]
With resolving https://github.com/hbz/lobid/issues/390 this issue can be closed.
